sentry-demos/empower

src/index.js
Using the `BrowserRouter` will cause errors because it create it's own
history object and sets that globally. This means it will interfere with
the history created by `createBrowserHistory()`, which is what Sentry
uses to navigate. To fix this, we switch to using the base `Router`,
which doesn't create it's own history, instead relies on the
external history we provide it.
=> fix(react): Use correct router

.gcloudignore, README.md, flask/main.py, src/components/Checkout.js, src/components/Products.js, tests/README.md, tests/endpoints.yaml, tests/requirements.txt
Used the mouse, did not run TDA
```
/ JS (auto)
```
```
/products JS (auto)
products Python (auto)
```
```
/cart JS (auto)
/checkout JS (auto)
checkout JS (custom)
checkout Python (custom)
error JS
error Python
/error JS (auto)
```
[40 Events](https://sentry.io/organizations/testorg-az/discover/results/?end=2021-07-06T22%3A12%3A00&field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=5808655&project=5808623&query=&sort=-timestamp&start=2021-07-06T22%3A07%3A22&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1), 8 Errors, 32 Transactions
```
for i in range(2)
py.test -s -n 1 frontend_tests
```
```
/ JS (auto) 4
```
```
/products JS (auto) 4
products Python (auto) 4
```
```
/cart JS (auto) 4
/checkout JS (auto) 4
checkout JS (custom) 8 …
```
=> TDA Testing

README.md, flask/main.py, src/components/Checkout.js, src/components/Products.js, src/components/ProductsJoin.js, src/index.js
- Set `se=<name>` tag on /products pageload so that it's retained for when the error gets made later.
- Verify it stays on scope across navigation state changes.
NOTE - email gets set in src/index.js and overrides the email in the checkout form (which gets passed in the request body). Email normally provided by session login or signup/checkout, and not right when a visitor lands on the home page.
NOTE - Getting the 'se' tag off of the sentry scope and having to set for every request's headers... could implement a new requests client so can hook into the request to set this (DRY).
NOTE - checking for 'se' tag in python as None or "undefined" because it's sometimes sent as "undefined" from frontend. We implement the change here in the before_request, or else have to instrument logic for …
=> query params trigger alert

flask/app.yaml, flask/db.py, react/app.yaml, react/src/components/Checkout.js, react/src/components/Complete.js, react/src/components/CompleteError.js, react/src/components/Products.js, react/src/components/ProductsJoin.js, react/src/index.js, react/src/utils/errors.js, tests/frontend_tests/test_add_to_cart.py
Update the ProductsJoin
- `/list` route
- `/about`
- `/employee/:id`
- try statement loop until /products are loaded
- `try/catch` for /products
- fixed fingerprint homepage error (Release Health), since it was having a different stacktrace per browser.
- updated error handling for /checkout should bring more consistent errors via TestDataAutomation.
Firefox and Chrome both error'd into same code block:
=> Error Handling Fetches

README.md, react/src/utils/errors.js
**Background**
Functionality already exists to force a crash to the demo application by passing the query param `crash=true`. Previously this would result in only one type of error, `UnhandledException`. Given there was only one error type, only one Issue in Sentry was created and it was therefore less realistic for demo purposes than being able to show a customer multiple errors.
**Updates in this PR**
- This PR adds a handful of other error types and chooses a random one to throw, when a crash is forced.
- The option to crash based on probability (i.e. 20% of the time with `crash=0.2`) should remain unchanged.
- See screenshot of sentry.io showing different Issue entries for each error type. Note that a `beforeSend` hook currently forces all `UnhandledException`s to be set to the same …
=> Throw random error on forced crash

react/src/components/Checkout.js, react/src/components/Products.js, react/src/components/ProductsJoin.js, react/src/index.js, react/src/utils/backendrouter.js
- Permit hitting different backend URLs based on a passed query parameter, i.e. `?backend=express`. 
- This will be used soon by me and Simon for our Springboot/Express onboarding tasks
- This is very easily extensible to any other type of backend we might want empower plant to support
✅ Should show up in `tags` in sentry.io
✅ Should hit different URLs depending on environment and specified backend type
✅ Should default to flask if no backend specified
✅ If an invalid backend type is specified, i.e. `?backend=invalid_type`, `alert` the user and proceed with using the flask backend.
✅ This should work whether accessing the homepage first and clicking through to products page, or, accessing the products page directly.
You can see that the `backendType` was reported to Sentry as a tag.
=> Route requests to different backend URLs based on backend-type query parameter

flask/main.py
This is the complement to client sdk fingerprinting done in React https://github.com/sentry-demos/application-monitoring/pull/34
The `se` tag was already being passed from the frontend, already parsed via request headers and set on scope as a tag (in app.before_request callback)
**New**
This PR parses the tag inside of before_send, and updates the fingerprint based on that.
**Note on Request Headers vs Query Params**
The se tag must be set via query params to the React and then sent via request headers. If you were hitting Python's /handled /unhandled endpoints directly (and skipping React)via Postman, then you'd have to include the se tag via request headers (or support would have to be added for something like localhost:8080/handled?se=will but I think that's overkill. Howe often would …
=> Python Fingerprinting

tests/conftest.py
- Point to the most recent release: https://github.com/sentry-demos/sentry_react_native/releases/tag/1.9
=> Update tests to point to React Native release 1.9

tests/README.md, tests/conftest.py
- Document how to handle an SSL Cert error that prevents one from running tests locally
- Small refactor to make the local fix for this error easier to make (1 line local change instead of 6)
=> SSL Cert error workaround documentation

flask/main.py
This is not the final code but it was an experiment that verifies this fix. See Files Changed for the final code.
The '111111' and '222222' still execute (and the event gets sent to Sentry) as long as you check if the 'se' key is in the scope first. This means you are no longer required to send through the se tag in the request headers (as is the case with our React Native app calling Flask)
```
def before_send(event, hint):
print("> 000000 code still executes...")
se = None
with sentry_sdk.configure_scope() as scope:
if 'se' in scope._tags:
se = scope._tags['se']
print("> 111111 code still executes...")
if se == "tda":
event['fingerprint'] = [ '{{ default }}', se, RELEASE ]
elif se not in [None, "undefined"]:
event['fingerprint'] = [ '{{ default }}', se]    
print("> 222222 code still …
```
=> Fix Before Send

tests/mobile_native/android/test_checkout_android.py
- Previously, the react native android test was not producing errors. This PR updates that test so that it scrolls to the correct location and clicks the checkout button, triggering the 500 error we expect.
=> Update test to produce desired error for automated test data

tests/README.md, tests/mobile_native/android_react_native/test_homescreen_react_native_android.py
This adds additional unhandled errors to React Native Android's TDA.
This lays the groundwork for Release Health in React Native.
'Crash Free Rate' is no longer stuck at '100%' as this new pytest triggers unhandled errors from button clicks on the home screen.
The randomization rate for erroring is set to 40%. Side Note: I realized there is no way to make it error 10% some days and 50% other days, because if you constantly pick a random number 1 to 10 over a 24hr period, it's always going to average out to 5 (think about it), which would give you 50%. So better just to pick a percentage, and I chose 40%. The code is simpler this way too.
Run it 10 times in a row, and should not get 10 crashes, because it only crashes 40% of the time.
```
py.test -s -n 4 …
```
=> React Native Javascript Crashes in Homescreen Pytest

README.md, tests/README.md, tests/desktop_web/test_homepage.py, tests/mobile_native/android_react_native/test_captureexception_react_native_android.py, tests/mobile_native/android_react_native/test_capturemessage_react_native_android.py, tests/mobile_native/android_react_native/test_nativecrash_react_native_android.py, tests/mobile_native/android_react_native/test_uncaughtthrownerror_react_native_android.py, tests/mobile_native/android_react_native/test_unhandledpromiserejection_react_native_android.py, tests/mobile_native/ios_react_native/test_captureexception_react_native_ios.py, tests/mobile_native/ios_react_native/test_capturemessage_react_native_ios.py, tests/mobile_native/ios_react_native/test_checkout_react_native_ios.py, tests/mobile_native/ios_react_native/test_nativecrash_react_native_ios.py, tests/mobile_native/ios_react_native/test_uncaughtthrownerror_react_native_ios.py, tests/mobile_native/ios_react_native/test_unhandledpromiserejection_react_native_ios.py
RN/iOS needed more tests
RN/Android needed homescreen to be split into multiple tests, per each button.
py.test -s -n 4 mobile_native/ios_react_native/test_capturemessage_react_native_ios.py
[event](https://sentry.io/organizations/testorg-az/discover/dustin-react-native:40617b96d9ee4164a5b3d30040c02b36/?field=title&field=event.type&field=app.device&field=user.display&field=timestamp&name=All+Events&project=5716557&query=%21event.type%3Atransaction+event.type%3Adefault&sort=-timestamp&statsPeriod=1h&yAxis=count%28%29)
py.test -s -n 4 mobile_native/ios_react_native/test_captureexception_react_native_ios.py
[event](https://sentry.io/organizations/testorg-az/discover/dustin-react-native:6ce82bd165764f069cd743fd0e1ecd7d/?field=title&field=event.type&field=app.device&field=user.display&field=tim …
=> React Native iOS and Android Tests

tests/mobile_native/android/test_anr_android.py, tests/mobile_native/android/test_handlederror_android.py, tests/mobile_native/android/test_nativecrash_android.py, tests/mobile_native/android/test_nativemessage_android.py, tests/mobile_native/android/test_unhandlederror2_android.py, tests/mobile_native/android/test_unhandlederror_android.py
We had a test for Checkout but not for the rest of the buttons which cause different error types.
These commands were run
```
py.test -s -n 4 mobile_native/android/test_unhandlederror_android.py
py.test -s -n 4 mobile_native/android/test_unhandlederror2_android.py
py.test -s -n 4 mobile_native/android/test_handlederror_android.py
py.test -s -n 4 mobile_native/android/test_anr_android.py
py.test -s -n 4 mobile_native/android/test_nativecrash_android.py
py.test -s -n 4 mobile_native/android/test_nativemessage_android.py
```
[Unhandlederror](https://sentry.io/organizations/testorg-az/discover/paranoid-android:82f30a9f6cec4867b4c6a9950d892e5d/?field=title&field=event.type&field=sdk.version&field=release&field=timestamp&name=All+Events&project=1801383&query=event.type%3Aerror&sort=-timestamp&st …
=> Android Native Tests for buttons

README.md, deploy.sh, react/src/index.js, react/src/utils/release.js, release.sh
The ./deploy.sh script is run daily. This will take care of uploading sourcemaps for the right release YY-M-Week. release.sh was updated to include the year. Running it "every 7 days" could get hard to time the cronjob with the exact 1st day of the week, so decided to run it daily instead for simplicity.
react/src/index.js was updated so that it uses a function `release()` to create the release in form YY-M-W. Every time the javascript app bundle is served, it will compute the release number dynamically.
[transaction with release 22.2.1](https://sentry.io/organizations/testorg-az/discover/application-monitoring-javascript:c95a70b336f0494b87ee43a3b10e5b25/?field=title&field=event.type&field=project&field=release&field=timestamp&name=All+Events&project=6089805&project=5808623&project=5808655 …
=> Release Versioning Update

react/src/index.js, react/src/utils/release.js
Now we see Package Name with the release.
Notice that only the release with Semantic Versioning is filterable by `release.version:22.2*`
and see it here
and see it here
[Trace ID: b3e0699afce24088a2c1dc31cf3cbe64](https://sentry.io/organizations/testorg-az/performance/trace/b3e0699afce24088a2c1dc31cf3cbe64/?pageEnd=2022-02-04T07%3A23%3A53.200&pageStart=2022-02-03T07%3A23%3A53.200)
I deployed this a moment ago, it's starting to get errors+tx's from TDA, you can track the Release here
https://sentry.io/organizations/testorg-az/releases/application.monitoring.javascript%4022.2.1/?project=5808623
=> Semantic Versioning - Package@Version

tests/conftest.py
React transactions getting dropped in Application Monitoring when it calls Express Application Monitoring backend.
React<>Express transactions not linked via Distributed Tracing
Bring up the OS X version in selenium to 10.13 which matches what was working in other successful OS X tests (e.g. OS X with Safari, 10.13).
Check the recent MacOSX:Chrome transactions from React to Express, they're now linked by distributed tracing.
[Discover Query](https://sentry.io/organizations/testorg-az/discover/results/?display=top5&field=browser.name&field=os.name&field=count%28%29&name=Error%3A+Not+enough+inventory+for+product&project=5808623&query=se%3Atda&sort=-browser.name&statsPeriod=1h&yAxis=count%28%29) for last Hour
If you see past 24Hours right now, you'll these transactions only started an hour …
=> standardized OS X versions for selenium

deploy.sh, react/src/index.js
**Problem1**
Our deploy script used sentry-cli but the release did not have the 'package name' in it for Semantic Versioning. Hence, source maps were getting uploaded to the '22.2.3' release but not the 'packageName@22.2.3' release.
Over the past 2 weeks I observed there were duplicate releases for both 22.2.2 and 22.2.3 getting created. One would have events in it, and the other would not.
**Problem2**
Also, fingerprinting in beforeSend was still using process.env.REACT_APP_RELEASE which was based on a .env file, which was a static value. Hence new releases 22.2.1 and 22.2.3 were still grouping with an outdated fingerprint.
**Solution1**
Both sentry-cli and the dynamically created Release in src/index.js now have packageName@release.
**Solution2**
Fingerprinting in beforeSend uses the …
=> Fix Release and Package Name

flask/db.py, flask/main.py, flask/requirements.txt
There are 3 different issues surfacing when Database connection and query problems occur. These problems occur intermittently. The erroring lines of code are from the ORM, SQLAlchemy and Python Socket being used, and this is not code we write, so it's hard at first glance to see where from our source code it's from (you must scroll to bottom of stack trace). These come from a mix of `get_products` `get_products_join` and `get_inventory` and all error on db.connect() or the sql query that's run.
One of these Issues is from BrokenPipeError. This is from deep within the sqlalchemy code so no known way to produce this locally. However I can pass bad arguments to db.connect('I cause failure') and the sql query so at least the new try/except blocks in this PR can be tested to some extent. 
When …
=> Database Connection Errors

README.md, flask/main.py, flask/requirements.txt, react/src/components/About.js
I had installed `requests` it during testing to my virtual env (pyenv) but never added it to requirements.txt.
Safari browsers don't have `Promise.allSettled` so using a different technique now. Need Safari13 (Selenium) in order for it to work.
`Promise.allSettled` does not throw exceptions, which is why we were advised to use it. But on second thought, we're pretty comfy using try/catch technique of throwing exceptions, rather than deal with Resolving/Rejecting promises.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled#browser_compatibility
Flask trace for /products + ruby /api 
https://sentry.io/organizations/testorg-az/performance/trace/134a7412942445f39c7ba1ec1ee86967/?pageEnd=2022-02-28T18%3A20%3A01.502&pageStart=2022-02-27T18%3A19%3A …
=> Flask requests package and React Promise update for Safari

flask/db.py, react/src/components/Checkout.js, spring-boot/README.md, spring-boot/pom.xml, spring-boot/src/main/java/com/sentrydemos/springboot/AppController.java, spring-boot/src/main/java/com/sentrydemos/springboot/Application.java, spring-boot/src/main/java/com/sentrydemos/springboot/DatabaseHelper.java, spring-boot/src/main/resources/application.properties.example
- **Springboot** - Upgraded sentry springboot sdk to 5.6.1
- **React** - renamed custom checkout transaction to 'Submit Checkout Form' which is what our react native demo app does now.
- **Flask** - fixed db error handling problem
HttpRestTemplate has been implemented in Springboot for making http requests.
Springboot **will soon** make http requests to Ruby. Currently the Ruby transaction gets made but is orphaned, it's not part of the trace with Javascript+Springboot, and so I commented out the ruby /api call in the springboot /products endpoint.
Springboot [transaction](https://sentry.io/organizations/testorg-az/discover/results/?field=title&field=event.type&field=transaction.op&field=project&field=sdk.version&field=timestamp&name=All+Events&project=6090082&query=url%3A%22http%3A%2F%2Fl …
=> Springboot http client RestTemplate

README.md, react/src/components/Employee.js, react/src/index.js, troubleshooting.md
Parameterized transaction names ([docs](https://docs.sentry.io/platforms/javascript/guides/react/configuration/integrations/react-router/#parameterized-transaction-names)) are useful to consolidate transactions (ex. `/teams/:teamid/user/:userid` instead of `/teams/123/user/345`).
This was tested successfully.
`beforeNavigate` is now used for parameterizing the Employee Page transactions, as `/employee/:id`
`<SentryRoute>` is _still_ used for parameterizing the Product Page transactions, as `/product/:id`
Using both, so we have an example of both, ready in our codebase at all times, for learning from, and experimenting, and debugging customer problems.
Showing 'before' so you can confirm the quality of the transactions is unharmed. I could not find significant differences between the two. …
=> Parameterize Transactions with beforeNavigate

react/run.sh
Local Empower Plant frontend source maps are not getting used which manifested in error `Cannot fetch resource due to restricted IP address`
The change is updating ./run.sh to use package name as a part of `RELEASE`; [matching react/src/index.js](https://github.com/sentry-demos/application-monitoring/blob/master/react/src/index.js#L49).
Before this change, [an Issue event's source maps are not applied](https://sentry.io/organizations/testorg-az/issues/3261093431/events/a5320aee02364a03bd1d5d09d7347b53/?project=5952962) and multiple releases are created (e.g. application.monitoring.javascript@2.2.2 and 2.2.2).
By applying this change, [source maps are applied as expected](https://sentry.io/organizations/testorg-az/issues/3261078026/events/533ff2f1ba714afab514e7947a48ffe3/?project=5952962) …
=> Updated RELEASE val with package

flask/main.py, flask/utils.py, ruby/main.rb
Type of Change:
Summary:
Ruby backend was not parsing the headers sent, so it was missing information like the `se`, `customerType` and `email` tags. Since the flask backend is also making a call to the ruby backend, I added the headers there as well.
Transactions
[link](https://sentry.io/share/issue/c019bc3c7fa6423f95e2ca699a5dcfac/)
=> Fix: Read headers in ruby

.gitignore, ruby/Gemfile.lock, ruby/README.md, ruby/main.rb
- Filter out OPTIONS and favicon.ico requests becasue the sdk will send them as transactions. We don't want transactions for these.
- Upgrade SDK to 5.4.1, from 5.0.1
- Removed sentry-ruby-core from Gemfile.lock, because sentry-ruby sdk no longer depends on it.
- added Gemfile.lock to source control because that's where the sentry-ruby sdk version is tracked.
Note: future sdk versions may auto filter out the OPTIONS requests. But we can leave our example in place because it's a good example, it should be harmless. Other platforms (sdks) still need this feature.
[the events in Discover](https://sentry.io/organizations/testorg-az/discover/results/?end=2022-08-10T13%3A28%3A00&field=title&field=project&field=http.url&field=http.method&field=trace&field=sdk.version&field=timestamp&name=All+Even …
=> Ruby Traces Sampler Filtering

react/src/components/Products.js
The /products response from the backend will soon serve more than 4 products, but we only have enough content to populate 4 of them on the frontend.
The backend will soon query more than 4 so that it creates a Performance Issue, as +5 sql queries in a N+1 query are needed in order to trigger a Performance Issue. Currently there are only 4 sql queries made in the 'products endpoints, not 5. It's +1 query to the sql reviews table for each product 'n, of which there are only 4.
This needs to be deployed to Prod before adding more rows to the products and reviews tables in the database.
[/products](https://sentry.io/organizations/testorg-az/discover/application-monitoring-javascript:2ba5d831e9ac4218962f958fee1f80c5/?field=title&field=event.type&field=project&field=user.display&field=timestamp& …
=> Frontend use only 4 Products

README.md, bin/sentry-release.sh, bin/source_diff_upstream.sh, bin/validate_dotenv.sh, bin/validate_dsn.sh, bin/validate_env.sh, bin/validate_project.sh, bin/verify_latest_code.sh, deploy.sh, env.sh, flask/run.sh, react/build.sh, react/package.json, react/src/components/Product.js, react/src/components/Products.js, react/src/components/ProductsJoin.js, react/src/utils/errors.js, react/validate_env.list, vue/build.sh
-  validate `.env` specifically, not exported env vars
-  validate_env for all projects, not just react
-  ability to run `npm start` w/ hot reload without running the entire `deploy.sh`
- `env.sh` standalone mode
-  set `RELEASE/REACT_APP_RELEASE` in temporary `.env` to fix Flask not sending right release
-  Remove eslint build-time warnings
-  Always do a clean build with `rm -rf build; npm install`
`./deploy.sh --env=local react`
`./deploy.sh --env=local react flask`
`./deploy.sh --env=staging react`
```
cd react
../env.sh local npm start
```
=> New deploy v0.2

.gitignore, react/package-lock.json, tests/conftest.py, tests/mobile_native/android/test_anr_android.py, tests/mobile_native/android/test_checkout_android.py, tests/mobile_native/android/test_handlederror_android.py, tests/mobile_native/android/test_nativecrash_android.py, tests/mobile_native/android/test_nativemessage_android.py, tests/mobile_native/android/test_unhandlederror2_android.py, tests/mobile_native/android/test_unhandlederror_android.py, tests/mobile_native/android_react_native/test_captureexception_react_native_android.py, tests/mobile_native/android_react_native/test_capturemessage_react_native_android.py, tests/mobile_native/android_react_native/test_checkout_react_native_android.py, tests/mobile_native/android_react_native/test_homescreen_react_native_android.py, tests/mobile_native/android_react_native/test_nativecrash_react_native_android.py, tests/mobile_native/android_react_native/test_uncaughtthrownerror_react_native_android.py, tests/mobile_native/android_react_native/test_unhandledpromiserejection_react_native_android.py, tests/mobile_native/ios/test_checkout_ios.py, tests/mobile_native/ios_react_native/test_captureexception_react_native_ios.py, tests/mobile_native/ios_react_native/test_capturemessage_react_native_ios.py, tests/mobile_native/ios_react_native/test_checkout_react_native_ios.py, tests/mobile_native/ios_react_native/test_nativecrash_react_native_ios.py, tests/mobile_native/ios_react_native/test_uncaughtthrownerror_react_native_ios.py, tests/mobile_native/ios_react_native/test_unhandledpromiserejection_react_native_ios.py
Update to all mobile tests to use a try/except block for handling exceptions
Update to all mobile tests to use `sentry_sdk` for capturing exceptions to Sentry
Breadcrumbs in the android->unhandled tests for now, because we're monitoring those very closely.
=> Mobile Test Monitoring

tests/conftest.py, tests/desktop_web/test_about_employees.py, tests/desktop_web/test_about_employees_vue.py, tests/desktop_web/test_add_to_cart.py, tests/desktop_web/test_homepage_vue.py, tests/desktop_web/test_subscribe_vue.py
and custom tags
`pytestName` still in use
I added:
`pytestPlatform` like desktop_web, android_react_native, android, ios
and `try/except` handling around the creation of selenium sessions in `conftest.py` for each pytest.fixture, before each individual test is run.
=> Selenium Session message capture for All Platforms

express/db.js, express/server.js, flask/db.py
PUBLIC_CLOUD_IP is not a var in config, but HOST already is (it's the IP address that PUBLIC_CLOUD_IP was trying to refer to) and HOST is already available in config.
Angelo and I found that if you pass `undefined` as the value (sometimes the calling Frontend doesn't pass it, or you're pasting the URL into the Browser URL bar and not setting headers), then this still evaluates to true, and it sets `customerType:undefined` and so express's /products's http call to Ruby fails on 
```
Server process(es) are running. Press Ctrl+C to terminate...
> /products headers { se: undefined, customerType: undefined, email: undefined }
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "se"
at ClientRequest.setHeader (_http_outgoing.js:536:3)
at new ClientRequest …
```
=> Fixes Express DB Config and Broken Boolean Evaluation of Headers

react/src/components/Checkout.js
This change attempts to optimize string literal concatenation during API request error reporting which has been notoriously for causing widespread client-side performance issues resulting in loss of revenue, appetite and migraines among our product leadership. We attempt to fix it in this PR by (1) reducing the redundancy in the number of operands and (2) using a more optimal method of concatenation.
If we were to believe [Peter Riesz](https://stackoverflow.com/users/1003150/peter-riesz)'s [benchmark from 2021](https://stackoverflow.com/questions/16696632/most-efficient-way-to-concatenate-strings-in-javascript?answertab=trending#tab-top) that tested both Chrome 86.0 and Node.js, `+` and `+=` are faster than `Array.prototype.join()` by a whopping factor of 3x, and are closely followed by …
=> Optimize string literal concatenation by eliminating operand redundancy

CODEOWNERS
Besides adding @thinkocapo and @realkosty as owners for /react
removed "react" entries without leading /, not sure why we have them - they make no difference
=> CODEOWNERS: update with @thinkocapo and @realkosty

tests/mobile_native/android/test_httperror_android.py
[ ] Bugfix
[ ] New Feature
[x] Enhancement
[ ] Refactoring
Adding test for Android HTTP Errors feature on our android demo that was added on this [pull request](https://github.com/sentry-demos/android/pull/48)
`test_httperror_android`
- [saucelabs test](https://app.saucelabs.com/tests/c652035bb6354dd78b72b02140714a32)
- [sentry error](https://sentry.io/organizations/testorg-az/issues/3779806734/?project=6749210&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=1h)
=> Adding HTTP error test

react/.npmrc, react/app.yaml.template, react/build.sh, react/package-lock.json, react/package.json
... and bump Google App Engine Node version 14 -> 16 to match.
This should work in GitHub Actions too... If it doesn't we can fix it by broadening version range.
This should be the "last" PR to include changes to `package-lock.json`. Going forward lets update minor versions only when we intentionally decide to.
https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-package-json
https://stackoverflow.com/questions/48524417/should-the-package-lock-json-file-be-added-to-gitignore
```
./deploy.sh --env=local react
```
```
deploy.sh --env=staging react
```
https://staging-application-monitoring-react-dot-sales-engineering-sf.appspot.com/error
Test error: https://sentry.io/organizations/testorg-az/issues/3146405066/events/662a9dda17c74ada89bd056e271b8828/? …
=> Require node 16/npm 8, don't update package-lock every build

react/package-lock.json, react/package.json
[v7.29.0](https://github.com/getsentry/sentry-javascript/releases/tag/7.29.0) includes [fix](https://github.com/getsentry/sentry-javascript/pull/6609) for the issue that's been causing us to not have LCP and some other web vitals as a result of transaction being finished prematurely: https://github.com/getsentry/sentry-javascript/issues/6470
**Errors**:
[7.29.0 sample event
](https://sentry.io/organizations/testorg-az/issues/3811538743/events/3b320b0127904b0dbaee4849671d08c5/?project=5808623)
**Transactions**: 
[7.17.3 - /products (pageload)
](https://sentry.io/organizations/testorg-az/performance/application-monitoring-javascript:6c31577e82824e08b2e6604938c21449/?project=5808623&query=sdk.version%3A7.17.3&referrer=performance-transaction-summary&statsPeriod=24h&transaction=%2Fproducts&uns …
=> Upgrade Sentry SDK from 7.17.3 -> 7.29.0

react/src/components/About.js, react/src/components/Organization.js, react/src/components/ProductsJoin.js
Switch to using `/organization` instead of `/products-join` (in addition to `/about`) for trends to avoid accidentally interfering with `/products-join`.
Move sleep from  `componentDidMount()` into `constructor()` in order to affect LCP instead of duration.
Right now LCP is not being captured because of transaction being cut short bug, so can't test it. Although we we can already make the observation that `ui.long-task` is not happening in `/organization`. This may not be a problem as long as it eventually contributes to LCP, although is a bit of a mystery.
https://github.com/sentry-demos/application-monitoring/pull/107
https://github.com/sentry-demos/application-monitoring/pull/124
[/about 1](https://sentry.io/organizations/kosty-org/performance/am-test:0edface1b1b1447c850a72650afc5a50/?p …
=> [react] Trends: attempt #2

bin/source_diff_upstream.sh, bin/verify_latest_code.sh
Deprecating `application-monitoring-deploy` broke `bin/verify_latest_code.sh`. This change fixes it.
Not tested in GH Actions environment, only locally, hopefully works.
(as part of deploying another change)
```
./deploy.sh --env=production express flask laravel spring-boot aspnetcore
```
=> [deploy] Update bin/verify_latest_code.sh to use application-monitoring-config

tests/mobile_native/android/test_nativemessage_android.py
[x] Bugfix
[ ] New Feature
[ ] Enhancement
[ ] Refactoring
The `test_nativemessage_android` test was not working. It was clicking the wrong list app button (HTTP Error button). I changed the selector to reflect the changes made to the list app
`test_httperror_android`
- [sentry error](https://sentry.io/organizations/testorg-az/issues/3864302185/events/688a8fa643f046b78e487e9d0cc63391/?project=6749210)
- [saucelabs error](https://app.saucelabs.com/tests/a7a1b590735d4ed08839d917ee6a0fd5)
`test_nativemessage_android`
- [sentry error](https://sentry.io/organizations/testorg-az/issues/3745924129/events/c69427928c684f669838bab3008e18e7/?project=6749210)
- [saucelabs error](https://app.saucelabs.com/tests/4a3bf3390ab3447abf474883ee5de41e)
[2.4.0 discovery …
=> Fixing selector for android native message test

README.md, react/src/index.js
Old closed PR: https://github.com/sentry-demos/application-monitoring/pull/130/files
Migration GitHub instruction: https://github.com/getsentry/sentry-javascript/blob/master/packages/replay/MIGRATION.md
New docs: https://docs.sentry.io/platforms/javascript/session-replay/
```
./deploy.sh --env=replay react
```
https://sentry.io/organizations/testorg-az/issues/3885985697/events/7c584b89b63047e5b9048507dcd31d33/?project=4504318060658688
https://sentry.io/organizations/testorg-az/replays/replay-application-monitoring-react:15069e3f67f8461e8ccc8cee202cdba5/?referrer=%2Forganizations%2F%3AorgId%2Fissues%2F%3AgroupId%2Fevents%2F%3AeventId%2F&t=48&t_main=console
=> Session Replay for react (sdk v7.29.0 w/ Replay migration)

tests/conftest.py, tests/desktop_web/test_about_employees.py, tests/desktop_web/test_add_to_cart.py, tests/desktop_web/test_add_to_cart_join.py, tests/desktop_web/test_homepage.py, tests/desktop_web/test_organization.py
```
SE_TAG=tda2 py.test -n 1 desktop_web
```
32 passed
=> [tda] Make list of backends and SE tag configurable in one place

aspnetcore/Startup.cs, aspnetcore/appsettings.json.template
TESTING Staging
[Automatic .NET performance instrumentation](https://testorg-az.sentry.io/performance/?project=4504461107396608)
[Distributed tracing on issues](https://testorg-az.sentry.io/performance/trace/904455a894c540a78e52bd9762be4081/?pageEnd=2023-02-18T01%3A10%3A52.252&pageStart=2023-02-17T01%3A10%3A52.252)
[Full trace of /Products](https://testorg-az.sentry.io/performance/trace/a64e919b94324dfc8466db2ac834a3cb/?pageEnd=2023-02-18T01%3A10%3A46.812&pageStart=2023-02-17T01%3A10%3A46.736)
NOTE: 
[N+1 is not implemented](https://testorg-az.sentry.io/performance/staging-application-monitoring-aspnetcore:a7e192fc9d0e49eb8e6d20d05f7497b8/?project=4504461107396608&query=http.method%3AGET&referrer=performance-transaction-summary&statsPeriod=7d&transaction=GET+Products&unselectedSeries=p100% …
=> [aspnetcore] - enabled tracing

tests/conftest.py, tests/desktop_web.sh, tests/desktop_web/test_about_employees.py, tests/desktop_web/test_about_employees_vue.py, tests/desktop_web/test_add_to_cart.py, tests/desktop_web/test_add_to_cart_join.py, tests/desktop_web/test_homepage.py, tests/desktop_web/test_homepage_vue.py, tests/desktop_web/test_organization.py, tests/desktop_web/test_subscribe_vue.py, tests/mobile_native.sh, tests/util/test_n.sh
The idea is to un-hardcode certain things to make it easier to develop and test new changes (e.g. freeze batch size at certain value and compare number of events generated BEFORE and AFTER the change) as well to make things generally more explicit. Tagging TDA's own errors with SE_TAG allows to easily check if anything failed in a development branch by separating test run failures from continuously-running 'tda' failures.
- `BATCH_SIZE` (default 1 instead of old randrange(20))
- use `SE_TAG` for TDA's own errors (default to system user, instead of old "tda")
- now need to explicitly supply `SE_TAG` and `BATCH_SIZE` in desktop_web.sh and mobile_native.sh
- default `SE_TAG` to system user
- include links to /issues in the report: GENERATED errors and OWN errors (filtered by `se` tag and …
=> [tda] Broad improvements: un-hardcoding configuration, better error reporting, etc.

tests/conftest.py, tests/desktop_web/test_about_employees.py, tests/desktop_web/test_about_employees_vue.py, tests/desktop_web/test_add_to_cart.py, tests/desktop_web/test_add_to_cart_join.py, tests/desktop_web/test_homepage.py, tests/desktop_web/test_homepage_vue.py, tests/desktop_web/test_organization.py, tests/desktop_web/test_subscribe_vue.py
- less code
- no need to remember to add the tag
- fixes some tests that were missing SE tag (e.g. `test_homepage_vue.py` - not sure if vue supports the tag but it doen't hurt)
tested as part of bigger set of changes
=> [tda] set SE tag URL parameter automatically for all webdriver GET requests

deploy.sh
prevents this from happening:
https://github.com/sentry-demos/application-monitoring/actions/runs/4228239243/jobs/7343489401
also potentially prevents accidentally getting billed for GAE Flexible storage
```
./deploy.sh --env=staging react
./deploy.sh --env=staging react
```
https://console.cloud.google.com/appengine/versions?project=sales-engineering-sf&serviceId=staging-application-monitoring-react
=> [deploy] Use same 'v1' version for ALL projects to avoid hitting GAE version max

flask/main.py, flask/utils.py
This reverts commit 4bfd719d4ad7cbe58d870fc6f988f27b5edc89ed.
- [Staging frontend still working](https://staging-application-monitoring-react-dot-sales-engineering-sf.appspot.com/products)
- [Staging flask backend still working](https://staging-application-monitoring-flask-dot-sales-engineering-sf.appspot.com/products)
- [Profile captured for flask backend (Without slow method)](https://testorg-az.sentry.io/profiling/profile/staging-application-monitoring-python/d5a11de7bb454c0ea58aa3865290fcec/flamechart/?colorCoding=by+system+vs+application+frame&fov=0%2C0%2C2188467968%2C18&query=&sorting=call+order&tid=68190858118912&view=top+down)
=> Revert "Add python profiling slow method (#183)"

flask/main.py, flask/utils.py
This should be an improved attempt to enable what (#183) attempted to do
The problem with #183 was that the slow method ran for way too long, disrupting the demo-flow for SEs. This iteration of the change implements a timeout of 4 seconds to make sure it does not go over it (In most cases it should not, but this is a safeguard)
- [staging event example](https://testorg-az.sentry.io/performance/staging-application-monitoring-python:4a0b3e06bc18445b98cd945171436adc/)
- url : https://staging-application-monitoring-react-dot-sales-engineering-sf.appspot.com/products
=> Add python slow method

express/db.js, flask/src/db.py, spring-boot/src/main/java/com/sentrydemos/springboot/DatabaseHelper.java
Hopefully this doesn't have any significant effect on DB load, but we'll find out.
Another option would have been:
`select *, pg_sleep(0.0625) from products` -> `select * from products, pg_sleep(0.0625)`
plugged every query into `psql` and made sure it returns something and doesn't fail.
=> [flask,express,spring-boot] Nicer SQL queries w pg_sleep() later in the query

flask/src/db.py
In addition to this code change also changing following in DB:
```
DROP VIEW product_bundles, backorder_inventory, weekly_promotions;
CREATE VIEW product_bundles AS SELECT CAST(pg_sleep(0.391) as TEXT);
CREATE VIEW backorder_inventory AS SELECT CAST(pg_sleep(0.8) as TEXT);
CREATE VIEW weekly_promotions AS SELECT CAST(pg_sleep(1.563) as TEXT);
```
FROM products: multiply timeout by 4 (number of products)
FROM reviews: multiply timeout by 6.25 (average number of reviews per product)
```
./deploy.sh --env=local react flask
```
http://localhost:3000/products
=> [flask] fix pg_sleep that's too short after moving it out of SELECT

aspnetcore/AppMiddleware.cs, aspnetcore/Empower.Backend.csproj, aspnetcore/appsettings.json
- Switch from warning to info logging of default messages emitted by the framework.  This will get us some built-in breadcrumbs.
- Add a custom log message to the middleware component.
- Bump to latest Sentry.NET SDK version
=> Add breadcrumbs for aspnet core

bin/projects_changed_bw_commits.sh
This is one of the steps toward having full CI/CD pipeline for all Empower projects.
Intentionally does not report changes to the following directories:
```
.github  (GitHub Actions workflows)
env-config
bin
vue   (no automated deployment yet)
ruby  (no automated deployment yet)
```
```
./bin/projects_changed_bw_commits.sh 9d826df5 7cb30b31
flask
```
```
./bin/projects_changed_bw_commits.sh dd3afdc7 7cb30b31 
express flask spring-boot tests
```
```
./bin/projects_changed_bw_commits.sh b521ac51 7cb30b31
aspnetcore express flask laravel react ruby-on-rails spring-boot tests
```
=> [platform] Script to detect projects changed between two commits

aspnetcore/Controllers/ProductsController.cs, aspnetcore/HardwareStoreContext.cs, aspnetcore/Program.cs
Revise #230  - Do the slowness in a DB interceptor so it looks like the query was slow, rather than a delay before the query.
=> Move slowness to interceptor

express/server.js
Fix unknown frame in express backend profiles
The express backend displays an unknown frame right before the getIterator frame. This is because that frame is coming from the /products route handler. 
So we need to explicitly define and call a method to handle the logic so that the profiler can pick up the name of the frame
[profile before](https://sergios-test-org.sentry.io/profiling/profile/express-backend/a99f9908cb8143d39485b758eac84edb/flamechart/?colorCoding=by+system+vs+application+frame&query=&sorting=call+order&tid=0&view=top+down)
[profile after](https://sergios-test-org.sentry.io/profiling/profile/express-backend/ba98adeff8124fb7a1b4eace8e336c5a/flamechart/?colorCoding=by+system+vs+application+frame&fov=0%2C0%2C13795618816%2C24&query=&sorting=call+order&tid=0&view=top+down)
=> add method to route handler

.github/workflows/cleanup_inactive_cloud_resources.yml, bin/cleanup_inactive_cloud_resources.sh
yml will be battle-tested
```
bin/cloud_resource_auto_shutdown.sh --project sales-engineering-sf --max-inactive-time-hours 24 --dry-run --service-id-contains staging
Service ID                               Environment   Last Request      Last Deploy       Deployer                Action Taken
staging-app-monitoring-aspnetcore        flex          > 1 days ago      65 days ago       matt.johnson-pint       delete (dry run)
staging-application-monitoring-aspnet... flex          > 1 days ago      127 days ago      kosty.maleyev           delete (dry run)
staging-application-monitoring-flask     standard      2 hours ago       65 days ago       kosty.maleyev           none
staging-application-monitoring-laravel   standard      > 1 days ago      186 days ago      katie.jenkins           delete …
```
=> [platform] Script + GH workflow to auto cleanup inactive GAE resources

react/src/components/Checkout.js, spring-boot/src/main/resources/application.properties.template
https://testorg-az.sentry.io/issues/4371253720/events/693a352fd9054916808cd1d70c5adc08/
Adding `v2` to `/checkout` query string should not break other backends but we might want to keep an eye out. I only tested Flask and it ~~works~~ breaks just fine: [sample event](https://testorg-az.sentry.io/issues/4117859548/events/0cc4093130a54cac9b150702f809a80f/)
=> [spring-boot] Enable capture of request body

react/package-lock.json, react/package.json
* Upgrade SDK to 7.61.1 which has bugfix for child spans
* Change all dependencies minor versions to use ~ instead of ^ in package.json in case somebody in the future runs `npm install` instead of `npm ci` (preferred), rollback locked versions back to those in package.json (@JonasBa please lmk if any of those were intentional/required for your change)
just basic: [example transaction](https://testorg-az.sentry.io/performance/staging-frontend-javascript:15bb9b650fbf4be5b661a29296fea7f9/?project=4504708328325120&query=transaction.op%3Apageload&referrer=performance-transaction-summary&showTransactions=recent&statsPeriod=5h&transaction=%2Fproducts&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29)
=> [react] upgrade SDK to 7.61.1; rollback all deps minor versions

react/src/components/Checkout.js
- Automatically fill out form with values per https://github.com/sentry-demos/empower/issues/250
- Easter egg: the address is for SF botanical garden
=> feat: fill form with default values for checkout

ruby/Gemfile, ruby/Gemfile.lock
webrick was picked because it does not depend on any native extensions -- meaning it is easier to install in a barebones docker image
=> ruby: add an application server to allow running standalone

react/build.sh, react/package.json
this simplifies calling `npm run build` since it does all the necessary parts so I can use this effectively in a dockerfile
=> react: perform all build-related parts in package.json:build

flask/src/db.py
prevents some mysterious `NoneType` errors when the environment variables are missing -- now it instead points at exactly what environment variable is needed
=> flask: fail on missing environment variables instead of later

tda/conftest.py
Some builds (not clear if those created in certain team member's laptops or those created using the new [make release](https://github.com/sentry-demos/ios/pull/47)target instead of XCode UI) have been crashing in SauceLabs simulator with EXC_BAD_ACCESS. We were able to reproduce that locally when building with XCode (not make) and using `iPhone 11 / iOS 14.5` (i.e. same version as in SauceLabs) as run destination in XCode, instead of default iOS 17 which ran fine. After finding the highest  (without needing to upgrade to Appium 2.x) platform version supported in SauceLabs - `iPhone 13 / iOS 15.5` I was able to successfully test that in the build doesn't crash on that iOS 15.5 simulator in XCode. I was additionally able to test that bumping the iOS version in SL using the existing latest …
=> [tda,ios] Bump iOS version to 15.5 to fix EXC_BAD_ACCESS in cli builds

tda/conftest.py
before:
```
<Module tda/desktop_web/test_about_employees.py>
<Function test_about_employees[desktop_web_driver0]>
<Function test_about_employees[desktop_web_driver1]>
<Function test_about_employees[desktop_web_driver2]>
<Function test_about_employees[desktop_web_driver3]>
```
after:
```
<Module tda/desktop_web/test_about_employees.py>
<Function test_about_employees[chrome@latest(Windows 10)]>
<Function test_about_employees[firefox@latest(Windows 10)]>
<Function test_about_employees[safari@latest-1(OS X 10.13)]>
<Function test_about_employees[chrome@latest(OS X 10.13)]>
```
=> prettier test names when parametrizing browsers

flask/requirements.txt
failing on:
```
Traceback (most recent call last):
File "/usr/local/bin/flask", line 5, in <module>
from flask.cli import main
File "/usr/local/lib/python3.11/site-packages/flask/__init__.py", line 7, in <module>
from .app import Flask as Flask
File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 28, in <module>
from . import cli
File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 18, in <module>
from .helpers import get_debug_flag
File "/usr/local/lib/python3.11/site-packages/flask/helpers.py", line 16, in <module>
from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.11/site-packages/werkzeug/urls.py)
```
=> upgrade flask to 3.x

tda/requirements.txt
this fixes rewrite warnings in 3.12
=> upgrade pytest to 7.4.2

tda/requirements.txt
6.0 is incompatible with python 3.12
=> upgrade pyyaml to 6.0.1

tda/README.md, tda/conftest.py
we should rotate the sauce credentials if someone has sent our creds in plaintext over http
=> [tda] security: remove option for saucelabs over http

react/src/components/Home.js, react/src/components/Nav.js, react/src/components/Products.js, react/src/index.js, tda/desktop_web/test_frontend_slowdown.py
Pass `frontendSlowdown=true` to trigger a frontend-only slowdown on a new `/products-fes` (fes = frontend slowdown) page.
- [Frontend-only slowdown - Pageload transaction](https://demo.sentry.io/discover/staging-react:0ed952bed76b4d489947018cdeff594d/?field=title&field=transaction.duration&field=transaction.op&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&homepage=true&name=All+Events&project=4504708328325120&query=title%3A%2Fproducts-fes&sort=-transaction.duration&statsPeriod=7d&yAxis=count%28%29)
- [Frontend-only slowdown - Navigation transaction](https://demo.sentry.io/discover/staging-react:901958b3359242f1ba1d914af4048285/?field=title&field=transaction.duration&field=transaction.op&field=event.type&field=project&field=user.display&field=timestamp&fie …
=> Implement Frontend-Only Slow Performance Story

flask/requirements.txt, flask/src/main.py
This PR adds the support of metrics to the `empower` org.
=> feat(ddm): Add support for metrics

auto-deploy.exclude, crons-python/deploy_project.sh
directly using `ssh` command doesn't seem to work in GHA, even after running `gcloud ssh-config`.
Instead of trying to figure out paths to known_hosts and key files, figured it would be simpler to just use `gcloud compute ssh`
local - OK
```
./deploy.sh --env=production crons-python
```
GHA:
tested that can connect with this approach
https://github.com/sentry-demos/empower/actions/runs/6885367036/job/18729396910
=> [crons-python] Attempt to fix deploy breaking in CI

tda/jobs/desktop_web.sh
Discussed disabling Vue in TDA with Neil and Prithvi until we have resources or help to fix it and agreed to move forward with it.
- missing sourcemaps
- no session replay
- se tag is not propagating
- no automated deployment
Because of above right now it’s unusable as entry point for a Vue demo and a hazard if somebody wants to click on “Parent” from flask error while doing a generic distr. tracing demo. Additionally it’s making it impossible for me to verify whether se tag is set 100% of the time in the backend for all other supported frontends and transactions, which is now a requirement for capturing events for “mock data” streaming
=> [vue] disable Vue in TDA

flask/src/main.py
Add a call to db.get_product in flask’s /organization endpoint so that we can get another “found in” endpoint on the query-summary page? Executes ~1% of the time /organization is hit.
https://github.com/sentry-demos/empower/blob/master/flask/src/main.py#L219-L221
https://github.com/sentry-demos/empower/blob/master/flask/src/db.py#L44
=> perform db query on /organization 1% of the time

react/src/components/About.js, react/src/components/Checkout.js, react/src/components/Home.js, react/src/components/Products.js, react/src/components/ProductsJoin.js, react/src/index.js
`se` tag which will be a requirement for "mock data" capture is missing on [a bunch of Flask endpoints](https://demo.sentry.io/discover/homepage/?field=project&field=transaction&field=count%28%29&id=21645&name=&project=5808655&query=se%3A%22%22+count%28%29%3A%3E1000+%21transaction%3Aproducts+%21transaction%3Acheckout&sort=-count&statsPeriod=30d&topEvents=5&yAxis=count%28%29) because it wasn't passed form frontend.
[example event (staging)](https://demo.sentry.io/issues/4647740264/?project=4504708328325120&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=3d&stream_index=0)
=> [react] automatically propagete tags (se, etc.) as headers for all fetch requests

react/src/components/Products.js
- addresses https://github.com/sentry-demos/empower/issues/306
- Replaces the cryptic `e` that is minified due to React limitations, with a human-readable `renderProducts()` function
- tested in staging ✅ 
⚠️ One thing that's not amazing is that we introduce [hooks](https://legacy.reactjs.org/docs/hooks-overview.html) to just one component in order to get this working. Whereas the other components in the app still do not use hooks. Hooks are modern React, and ideally we will rewrite all components in the app to use hooks -- which I wouldn't expect to be that difficult 🤞. But I think it's OK to rewrite components in phases, as general maintenance, and get this PR out there awhile.
- [Transaction](https://demo.sentry.io/discover/staging-react:42511f28bc86492abb07d36d9c0d2b9e/?field=title&fie …
=> [React] Make browser profile frame human readable

tda/deploy_tda.sh
As of right now if you delete or rename a code file it won't be deleted from deployment host. That's a problem when that file is a test, resulting unwanted test being run as pytest collects everything from directory
=> [tda] sync file deletion/rename correctly when deploying TDA

flask/requirements.txt
Motivation:
Hoping this fixes missing SE tag ([discover query](https://demo.sentry.io/discover/homepage/?end=2023-11-28T06%3A28%3A16&field=project&field=transaction&field=count%28%29&field=browser.name&field=client_os.name&field=event.type&id=21645&name=&project=5808655&query=count%28%29%3A%3E0+se%3A%22%22&sort=transaction&start=2023-11-28T05%3A28%3A16&topEvents=5&yAxis=count%28%29)) on some transactions even though [we set it for all routes using @app.before_request](https://github.com/sentry-demos/empower/blob/9d29e3714878497860d20cc0c518ce2e0ff5ce16/flask/src/main.py#L261C20-L265).
```
./deploy.sh --env=staging flask
```
Filled out [Demo Data Requirements Matrix](https://www.notion.so/sentry/9366b129ce4745a7a40555a1d3b06467?v=02e3a592c3f543a79723158d9ad66953&pvs=4) based on current …
=> [flask] bump Sentry SDK: 1.34.0 -> 1.37.1

react/src/components/Products.js
Looks like part of https://github.com/sentry-demos/empower/pull/331 got mistakenly overwritten in a subsequent conflict merge. This fixes it.
none
=> [react] fix mis-merge of PR #331

flask/src/main.py, react/src/components/Organization.js, react/src/components/Products.js
The 2 flask endpoints corresponding to (un)compressed assets are missing SE tag ([discover query](https://demo.sentry.io/discover/homepage/?field=project&field=transaction&field=count%28%29&field=browser.name&field=client_os.name&field=event.type&field=sdk.version&id=21645&name=&project=5808655&query=se%3A%22%22+%21browser.name%3A%5Bokhttp%2CEmpowerPlant%2Csentry_react_native%5D&sort=transaction&statsPeriod=2h&topEvents=5&widths=-1&widths=277&yAxis=count%28%29))
deployed react and flask to staging, 
hit /products and /organization with ?se=kosty in react
✅[send_report_configured_properly transaction](https://demo.sentry.io/performance/staging-flask:9718438469854d0a92390758c03e1e2e/?project=4504331063525376&query=http.method%3AGET&referrer=performance-transaction-summary&showTransactions=re …
=> [react][flask] fix missing SE tag for un/compressed_assets

flask/requirements.txt, flask/src/main.py
This PR bumps the sentry-sdk dependency and adds additional metrics to the flask application.
Closes https://github.com/getsentry/sentry/issues/60373
=> feat(ddm): Add new metrics and bump sentry-sdk to 1.38.0

flask/src/main.py
Make `get_iterator` faster by 2 seconds needed to bring down React LCP p75 down to 5.5s from 7.5s so that the horizontal line in web vitals corresponding to LCP on the right has some thickness to it and looks good in the demo.
=> [flask] reduce /get_iterator span from 4s to 2s to fudge LCP p75

flask/requirements.txt
Update `sentry-python` to `1.39.2` in order to fix missing GH linking on Query Source ([example](https://demo.sentry.io/performance/database/spans/span/496db2bc74e1e116/?project=5808655&statsPeriod=1h))
After the update, it looks like [this](https://demo.sentry.io/performance/database/spans/span/44fb837cac2f206c/?project=5808655&statsPeriod=1h)
=> Update to sentry-python 1.39.2 to fix GH linking in Query Source

README.md
Noticed that the `Run` instructions look, at a glance, as if one is supposed to run them sequentially. It would be better to make it extra clear that you pick between two options.
=> Make README start instructions clearer

tda/.sauce_credentials, tda/desktop_web/test_checkout.py
From the devs:
> I have a wild guess, but would it be possible to add some timeout (maybe 2 seconds) between the initial /products page load and the navigation to the checkout cart?
> The issue might have something to do with transaction boundaries + selenium. I notice that there's no issue on the /products when using my own browser.
> if you take a look at this replay, it looks like the navigation to /cart happens immediately after the /products page is loaded and the sdk doesnt have any time to resolve the pageload transaction https://demo.sentry.io/replays/98f5eaa4fa86415e963b2b89ef6f3839/?referrer=%2Fperformance%2F%3AeventSlug%2F&t=5.901&t_main=network
Neil: yep, let me try this
=> add two seconds to see if that helps with webvitals issue

flask/requirements.txt, flask/src/main.py
> we fixed the bug with query source not being attached to some spans & we turned collecting query source on by default in [Python SDK 1.40.0](https://github.com/getsentry/sentry-python/releases/tag/1.40.0).
=> update python-sdk to 1.40.0 to fix query-source (now on by default)

mini-relay/classify_data.py
this should allow us to re-enable the check here
ideally tags would be forwarded along with `metric_meta` and `statsd` and then these could get classified 🤔
=> [mini-relay] ignore unclassifiable metric_meta envelopes as well

react/src/index.js
experimental feature ui.click transactions may be overwriting navigation transactions in the demo. 
Abhi: 
> perhaps theres a race condition here. Considering ui interactions are experimental and not actively supported, should we turn this off for the demo?
**Will C (Wed Jan 24 2024)**
Can anyone fill me on on what the ui.action.click for /products is about?
or link me to a PullRequest?
I opened it, it appears like a pageload txn, it has spans you’d find in a pageload
22 replies
**Will C**
The TPM indicates it’s probably being done via TDA, is that the case?
Not asking for either of the /products /products to be removed.
Just looking to be aware of any potential differences or plans regarding demo’s or the architecture of our app.
**Kosty M**  
weird
**Chris S**
Probably this? …
=> Remove experimental feature for ui clicks, which may be overwriting navigation transactions

.github/workflows/deploy_tda.yml, tda/deploy_tda.sh
Enable running `tda/deploy_tda.sh` in GitHub Actions through manual dispatch
https://github.com/sentry-demos/empower/actions/runs/8365685181/job/22904112535
=> [platform] GitHub Actions workflow to deploy TDA

react/package-lock.json, react/package.json, react/src/index.js
Updates sentry react to 7.108.0 and turn on the `enableInp` flag in the browser tracing integration.
=> Bumps sentry react sdk to 7.108.0 and toggle enableInp to true

react/src/index.js
I didn't test this since it's such a simple change, but what could go wrong, right? Right? 😅 
I know we're masking them in sentry, but there are still opportunities for this to be problematic. Better to just fix it at the source. Example 'problem' is this showing up:
Sometimes marketing or docs needs to take screenshots, so might as well just use example.com everywhere
=> switch dummy emails from gmail to example.com

react/src/components/About.jsx
I misunderstood how sentry contexts work: didn't realize they were global. This changes how we attach the LaunchDarkly context to be in its own scope after the feature flag evaluation. This will stop errors that aren't related to the flag from being associated with the flag. I believe that issue (other errors getting associated with the context) is the issue you're seeing with the error rates. I was able to test this and observe that the LaunchDarkly context is only being attached to the errors generated when the flag was evaluated.
This isn't an issue customers will need to worry about. Customer applications won't have such a high rate of errors, so that noise won't be present in their apps.
One other thing to note. Before testing this, be sure to stop your measured rollout and start a …
=> Attach context on scope

.github/workflows/auto-deploy.yml
- Sorry in advance about formatting diff 😞 [Real changes are these lines](https://github.com/sentry-demos/empower/pull/512/files#diff-39749da973a6d7b52c07bb6bc3a69ed00b12326959c832a3bc3b7b35eb12328cR72-R92)
- Trying to get rid of `?` on coverage delta [here](https://github.com/sentry-demos/empower/pull/463#issuecomment-2091930560)
- Codecov team suggests that it's due to difference between how our yml files upload codecov reports: `auto-deploy.yml` uploads reports with no flags, but `run_codecov_on_pull_request.yml` uploads reports with flags `api` and `frontend`.
- This PR would adjust `auto-deploy.yml` to set those flags as well.
=> Ensure codecov flags get uploaded upon merge to master branch

.gitignore, tda/conftest.py, tda/mobile_native/android_react_native/test_captureexception_react_native_android.py, tda/mobile_native/android_react_native/test_capturemessage_react_native_android.py, tda/mobile_native/android_react_native/test_checkout_react_native_android.py, tda/mobile_native/android_react_native/test_homescreen_react_native_android.py, tda/mobile_native/android_react_native/test_nativecrash_react_native_android.py, tda/mobile_native/android_react_native/test_uncaughtthrownerror_react_native_android.py, tda/mobile_native/android_react_native/test_unhandledpromiserejection_react_native_android.py, tda/mobile_native/ios_react_native/test_captureexception_react_native_ios.py, tda/mobile_native/ios_react_native/test_capturemessage_react_native_ios.py, tda/mobile_native/ios_react_native/test_checkout_react_native_ios.py, tda/mobile_native/ios_react_native/test_nativecrash_react_native_ios.py, tda/mobile_native/ios_react_native/test_uncaughtthrownerror_react_native_ios.py, tda/mobile_native/ios_react_native/test_unhandledpromiserejection_react_native_ios.py
For ios, we needed to use more recent version of appium to hide_keyboard since it comes up intermittently. For Android, now clicking on first textbook to populate textfields
=> Selectors reflect app v3.0.1

react/package-lock.json, react/package.json
I've noticed a discussion about pageload transactions missing since the bump to the v8 SDK. This seems to happen with replay integrations + chrome and has been fixed with https://github.com/getsentry/sentry-javascript/pull/12933.
=> chore(react): Bump to latest sentry react sdk

react/src/index.js
- We capture bits of data in the scope, later pulling it out to send it to the backend as headers. We also pull this data out in beforeSend and another place or two.
- This results in triggering performance issues for the demo
- During the v8 upgrade, we swapped out calls to set tags on the scope with, `Sentry.setTag()` (works on the isolation scope). That broke this functionality and performance issues stopped getting triggered with individual SEs' tags. this PR restores it
=> Fix metadata (se, email) stored in scope

express/app.yaml.template, express/package.json
✅ (loads something) https://staging-application-monitoring-node-dot-sales-engineering-sf.appspot.com/products
✅ (standard demo flow) https://staging-application-monitoring-react-dot-sales-engineering-sf.appspot.com/?se=express-node-upgrade-14-to-18&back
Still waiting for some txns to arrive delayed by INC but looks within the same range
https://demo.sentry.io/discover/homepage/?display=top5&field=transaction&field=p50%28transaction.duration%29&field=min%28transaction.duration%29&field=max%28transaction.duration%29&field=count%28%29&id=21645&name=&project=4504330844635136&query=event.type%3Atransaction+transaction%3A%22GET+%2Fproducts%22&sort=-transaction&statsPeriod=24h&topEvents=5
end=express
=> [express] upgrade Node 14.x -> 18.x (GCP dropped support)

codecov.yml
with these changes, we should see components -> flags -> files in the PR comment. The PR comment in this PR doesn't show files because no files covered by tests were changed and no new files were added.
=> put flags and components next to each other in codecov PR comment

react/src/index.js
https://docs.sentry.io/platforms/javascript/migration/v7-to-v8/#change-of-replay-default-options-unblock-and-unmask
Let's actually follow migration docs next time 😄
BEFORE
AFTER
=> fix replay .sentry-unblock after v7->v8 everything is ******

crons-python/requirements.txt, flask/requirements.txt, flask/src/main.py, tda/requirements.txt
- Bumped Python SDK to 2.4.0. There have been no breaking changes in the API that we're using in Empower, so no code changes necessary.
- Removed one unused import.
=> Bump Python SDK version

auto-deploy.exclude
currently breaking our pipeline https://github.com/sentry-demos/empower/actions/runs/11432793019/job/31803804101
I wonder if Vercel's bot will now post in all commits in this repo (this one modified file in root directory, not next).. maybe there's a way to limit it to changes in `next` directory only? I'd say it's not a big deal except that it adds noise to codecov demo. @ndmanvar what do you think?
=> Exclude Next from auto-deploy since it has it's own Vercel automation

flask/src/main.py
- Conditional for sleep time should check sleep_time not time_delta
Example [error](https://demo.sentry.io/issues/6131235906/events/3235cb0fb30d45da956bc065ad6f562b/?project=5808655)
=> Fix sleep time conditional

react/src/components/Products.jsx, ruby-on-rails/app/controllers/api/v1/products_controller.rb
this introduced a few unwanted changes in addition to the fix https://github.com/sentry-demos/empower/pull/655
=> [react, rails] rollback some unnecessary changes in autofix-generated PR #655

flask/src/main.py
- flask_cache_ was being added as a default key prefix which interfering with it showing up in the Sentry UI
=> Override default flask_caching key prefix

tda/conftest.py
This should make graphs a little smoother
If this is not enough we can switch to 6-day cycle (or 14/30-day to match what SE will often have as time interval during demos)
Eventually we want this to be on a 6 week cycle to match releases (can now be overlayed in dashboards)
=> [tda] Critical Experiences - switch to 24 hour cycle

.github/workflows/auto-deploy.yml, .github/workflows/run_codecov_on_pull_request.yml
Alternatively we could put something like
```
cat jest-junit.xml | grep FAIL -A 10
```
after that `||`
but I don't see value in actually maintaining those tests. Lmk if I'm missing something
=> [codecov] make npm test --coverage always succeed even if some test fails

.github/workflows/run_codecov_on_pull_request.yml, react/src/tests/Products.test.js
although I think we should make `npm test --coverage` pass regardless if tests succeed or fail
=> [react] fix Products.test.js failing after PR 667; rename codecov.yml

tda/conftest.py
1)
- smaller segments of error/slow
- no back-to-back segments of error/slow, “normal” segments in between
- same 24h total cycle
- 5 hours success, then 1 hour failure (one of 4 possible), then another 5 hours success, etc.
`-----_-----_-----_-----_`
2) when failing, don't fail 100% of the time, just 30% of the time (to be more realistic)
```
RUN_ID=critexp-better-schedule python3 -m pytest -s -n 3 desktop_web/test_checkout.py
======================================================================================= test session starts =======================================================================================
platform darwin -- Python 3.13.1, pytest-7.4.2, pluggy-1.5.0
rootdir: /Users/kosty/home/emp3/tda
plugins: forked-1.4.0, xdist-3.1.0
gw0 [4] / gw1 [4] / gw2 [4]
.... …
```
=> [critexp] new segment schedule and probabilities

deploy.sh
when no celery process present deploy.sh would return -1 which was confusing and would break CI
`./deploy.sh --env=local flask`
http://127.0.0.1:8181/products
Cmd+C
`./deploy.sh --env=local flask`
http://127.0.0.1:8181/products
Cmd+C
`./deploy.sh --env=local flask`
http://127.0.0.1:8181/products
Cmd+C
=> [platform, flask] fix deploy.sh exit code by not killing celery

tda/desktop_web/test_subscribe.py
- Subscribe tda test was cycling through backend query params. 
- However, the only backend with the subscribe queue feature is flask. 
Testing
- Deployed to sauce locally and saw successful test run
=> [tda] Removes query param from the url 

flask/src/main.py, flask/src/queues/email_subscribe.py, flask/src/queues/tasks.py
- Custom instrumentation was creating a transaction within a transaction, resulting in the sdk not picking up the real error rate
- Remove custom instrumentation means the sdk will infer the name
-- retry now has same transaction name as consumer
-- main produce is named after function endpoint "enqueue"
**Before**
**After**
=> [flask] Fix error rate by removing custom instrumentation

bin/sentry-release.sh
`sentry-cli releases files upload-sourcemaps` has been deprecated in favor of `sentry-cli sourcemaps upload` for quite some time now. Keeping this code around in the demo repo has confused folks who are unaware of this deprecation.
=> ref(cli): Don't use deprecated `sentry-cli` command

bin/envsubst.sh
was breaking `app.yaml.template` in `ruby-on-rails`
https://github.com/sentry-demos/empower/blob/aec789c56c24a13a3ac2091ac271919ae561c699/ruby-on-rails/app.yaml.template#L1
./deploy.sh --env=staging ruby-on-rails
http://staging-application-monitoring-rails.sales-engineering-sf.appspot.com/products
=> [platform] fix envsubst handling of escaped \$

bin/envsubst.sh, react/build.sh
also switched to portable envsubst and fixed another edge case in it (no newline at end of template file)
```
./deploy.sh --env=staging react
.
.
.
[sentry-webpack-plugin] Info: Sending telemetry data on issues and performance to Sentry. To disable telemetry, set `options.telemetry` to `false`.
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
> Found 2 files
> Analyzing 2 sources
> Analyzing completed in 0.015s
> Adding source map references
> Bundling completed in 0.131s
> Bundled 2 files for upload
> Bundle ID: 51c9329d-47ff-54b9-a048-1d0655748d23
> Optimizing completed in 0.005s
> Nothing to upload, all files are on the server
> Processing completed in 0.208s
> File …
```
=> [release] fix sourcemap <-> release association

tda/mobile_native/android/test_checkout_android.py
**Experiment details**
Run `python3 -m pytest -n 1 mobile_native/android/test_checkout_android.py` with different conditions:
1. No change: [Replay](https://demo.sentry.io/replays/76a4a278b57e407580a7d4fccf14e67c/?referrer=%2Fissues%2F%3AgroupId%2Fevents%2F%3AeventId%2F&t=3.144300000011921&t_main=errors), where no flagship error appears as expected
2. Change from `2` to `3` (in `time.sleep(3)`): [Replay](https://demo.sentry.io/replays/0fa42fe5302644639c98ac6449b0d0bd/?referrer=%2Fissues%2F%3AgroupId%2Fevents%2F%3AeventId%2F&t=4.7679000000357625&t_main=errors), where the [MainFragment$BackendAPIException](https://demo.sentry.io/issues/6530181600/events/9de3f96cddc148f7921687aa7b07f318/?project=4508968118321152&referrer=replay-errors) appears as expected
Therefore, change `time.sleep(2)` to …
=> add 1s to time.sleep

express/app.yaml.template, express/package-lock.json, express/package.json
GCP has announced deprecation of node18, therefore we need to upgrade
=> chore: upgrade Node.js version to 20.x.x in Express service

ruby/build.sh, ruby/main.rb
`./deploy.sh --env=production ruby`
https://demo.sentry.io/stats/?dataCategory=spans&project=4508972558516224&statsPeriod=1h
=> [ruby] fix DSN missing because .env was ignored by gcloud deploy

bin/sentry-release.sh, bin/validate_dotenv.sh, bin/validate_env.sh, deploy.sh, env.sh
- migration to team-se requires new sentry auth token
- added auth token in gcloud
- updated script to conditionally fetch based on env
- moved auth token fetching to be before source maps upload to fix org mismatch deployment bug
- may have only existed on my local but we need to override whatever is in SENTRY_AUTH_TOKEN with the correct env secret
- updated validate_env for better logging
TESTING
- Successfully deployed locally + staging
=> Fix failing staging deployments + google secret manager

react/src/index.js
Added all urls to `networkDetailAllowUrls` configuration to see Response and Request information at Session Replay Network -> Response/Request tabs
=> Updated URLs for Session Replay network details

tda/jobs/desktop_web.sh, tda/jobs/mobile_native.sh
Something happened when this was deployed..
This reverts commit 407fb85d6067859b8b93c5e4319e493fedc3cebf.
=> Revert "[tda] increase number of threads 8 -> 16 (#833)"

aspnetcore/Program.cs
I think it's best we disable until it gets a bit better:
See:
* https://github.com/sentry-demos/empower/issues/850
* https://github.com/getsentry/sentry-dotnet/issues/4262
* https://github.com/getsentry/sentry-dotnet/issues/4263
=> aspnetcore disable blocking detection

deploy.sh
- project_id isn't specified locally causing tunnel to not setup correctly
- staging/prod project_id isn't required as we are already in that project
Testing
- deployed to local and staging successfully
=> Set project id for flask deployment

flask/src/db.py, flask/src/main.py
Implemented as chained exception (`raise ... from ...`). This way SEs are not confused and will see familiar-ish inventory error. Same can be done for Option 1 (https://github.com/sentry-demos/empower/pull/857)
This is designed not to break Critical Experiences (see `validate_inventory`)
This is mutually exclusive with Option 1 (https://github.com/sentry-demos/empower/pull/857) we have to pick one or the other depending on which one provides a better Seer demo.
http://localhost:3000/?cexp=standard_checkout_fail&se=unboundlocalerror2-cexp-standard_checkout_fail
[flagship error, N+1 query](https://kosty.sentry.io/issues/?project=4506005091319808&query=se%3Aunboundlocalerror2-cexp-standard_checkout_fail&referrer=issue-list&statsPeriod=30d) …
=> [flask, seer] autofixable flagship error - UnboundLocalError - OPTION 2 [chained]

tda/build.sh, tda/deploy_tda.sh
Trying to fix this:
https://github.com/sentry-demos/empower/actions/runs/16126796262/job/45505551185
```
Error: [Errno 13] Permission denied: '/home/kosty/empower-tda/env/bin/activate.fish'
```
seems like when running  `./deploy_tda.sh` locally from my laptop it used a different user (`kosty`) to create `activate.fish` than the user when the script is run in GHA (user: `runner`). Not sure why that file was created... probably Ubuntu auto-updated minor version of `python3.10` and its `venv` module started supporting this new shell... 
```
cd tda && ./deploy_tda.sh
```
Go nuclear and delete entire `env` dir during every deployment
not touching this line as it's probably there for a reason...
```
ssh $HOST 'find '$DIR' ! -path "*/__pycache__/*" ! -path "*/empower-tda/env/*" ! -path …
```
=> [tda] always re-install requirements.txt when deploying

tda/deploy_tda.sh, tda/logrotate.d/tda
this broke after `sudo apt upgrade` + reboot
`./deploy_tda.sh`
=> [tda] fix permissions for logrotate after package version upgrade

tda/jobs/desktop_web.sh, tda/jobs/mobile_native.sh
Let's reduce number of pytest threads back to what it used to be to see if it helps with TDA getting stuck/deadlocked
=> Revert "Reapply "[tda] increase number of threads 8 -> 16 (#833)" (#837) (#838)"

tda/conftest.py
Not tested since pretty trivial
=> [tda] remove 'ruby' from list of react backends in conftest.py

react/src/components/Products.jsx, react/src/index.js
Generate less of Slow DB Query and N+1 Issue spans so we can elevate `500 - Internal Server Error` to the top of Issue feed
TDA changes will follow. Basically some of the (non-CritExp) test flows will use /products-join and always error in checkout changing overall numbers.
https://github.com/sentry-demos/empower/pull/947
`./deploy.sh --env=local react`
http://localhost:3000/?api=join&backend=flask -> click Products
http://localhost:3000/?api=join&backend=express -> click Products
http://localhost:3000/?api=join&backend=springboot -> click Products
http://localhost:3000/?api=join&backend=rails -> click Products
http://localhost:3000/?api=join&backend=aspnetcore -> click Products
http://localhost:3000/?api=join&backend=laravel -> click Products
=> [react] add ?api=join to use /products-join

react/src/components/About.jsx, tda/desktop_web/test_checkout.py, tda/desktop_web/test_frontend_slowdown.py, tda/desktop_web/test_products_join.py, tda/desktop_web/test_rageclick.py
Previously we removed Ruby as `?backend=` option in TDA globally (https://github.com/sentry-demos/empower/pull/933) to get rid of some unintentional errors in `/about`
This cleans up all other tests that were excluding it already. Looks like it was also used in `test_homepage`. Pretty sure that was also not intentional
=> [tda,ruby] clean up backend(exclude='ruby') now that we removed it entirely

tda/conftest.py, tda/desktop_web/test_checkout.py, tda/jobs/desktop_web.sh
Make `500 - Internal Server Error` = flagship + Seer demo to show up at the top without needing to search for it 
[sankeymatic_20250718_120229_source.txt](https://github.com/user-attachments/files/21321848/sankeymatic_20250718_120229_source.txt)
1. modify `desktop_web.sh` locally just for testing setting average `BATCH_SIZE=10` 
2. RUN_ID=tda-flask-flagship-bypass-cexp-AFTER ./jobs/desktop_web.sh
3. git reset --hard HEAD~1
4. modify `desktop_web.sh` locally just for testing setting average `BATCH_SIZE=10` 
5. RUN_ID=tda-flask-flagship-bypass-cexp-BEFORE ./jobs/desktop_web.sh
```
RUN_ID=tda-flask-flagship-bypass-cexp-AFTER ./jobs/desktop_web.sh
======================================================= test session starts =======================================================
platform darwin …
```
=> [tda] elevate flagship by bypass CExp, re-attempt checkout, /products-join

tda/desktop_web/test_rageclick.py
- [primary] Elevate `500 - Internal Server Error` higher in the issue stream (see https://github.com/sentry-demos/empower/pull/955)
- runs faster
```
RUN_ID=tda-test-rageclick-use-products-join-2 python3 -m pytest -s desktop_web/test_rageclick.py
======================================================= test session starts =======================================================
platform darwin -- Python 3.13.3, pytest-7.4.2, pluggy-1.6.0
rootdir: /Users/kosty/home/emp4/tda
plugins: forked-1.4.0, xdist-3.1.0
collected 4 items                                                                                                                 
desktop_web/test_rageclick.py SauceOnDemandSessionID=47541a4c4ab84f3f8b64e96950d986e3 job-name=test_rageclick[chrome_windows] …
```
=> [tda] test_rageclick to use /products-join to create less perf issues

react/src/index.js
Seer when run automatically will use the latest event. We want it to run on event using flask backend (for which we have increased TDA volume in https://github.com/sentry-demos/empower/pull/955) instead of taking chances with other backends where we haven't tested autofix performance.
Before this we had a Grouping rule accomplish this but it doesn't cover sandbox and can be accidentally removed.
`./deploy.sh --env=local react`
=> [react] split out flagship + backendType:flask into separate issue

react/src/index.js, tda/desktop_web/test_checkout.py
Elevate Laravel flagship relative to Laravel performance issues now that it's (reasonably) realistic and autofixable
#955
#972
#962
`./deploy.sh --env=local react` -> go through checkout flow, verify error in Sentry
```
RUN_ID=tda-add-laravel-to-cexp-bypass python3 -m pytest -s desktop_web/test_checkout.py
=============================================================== test session starts ===============================================================
platform darwin -- Python 3.13.3, pytest-7.4.2, pluggy-1.6.0
rootdir: /Users/kosty/home/emp4/tda
plugins: forked-1.4.0, xdist-3.1.0
collected 4 items                                                                                                                                 
desktop_web/test_checkout.py …
```
=> [tda,react] Add laravel as 'preferred' backend to CExp bypass flow

react/src/components/Checkout.jsx
move `checkout.order.total` attribute declaration up so that it gets attached to events when checkout succeeds and fails. Currently, only gets attached if it succeeds. But it would be useful to have it to build widgets for "Total Revenue Lost" which seems to be a popular use case
=> add cart total in failed and succesful checkout

tda/conftest.py, tda/mobile_native/android_flutter/test_checkout_flutter_android.py
- stream Flutter data to `demo` and `sandbox` (errors, spans, replays, logs, profiles).
- remove some legacy features in TDA
Using build based on latest updates by @Prithvirajkumar (no PR??) https://github.com/sentry-demos/flutter/commits/main/
Build has been uploaded as `1.0.0` - **next time when updating please just overwrite 1.0.0, no need to create new release**, creating new ones increases complexity with nothing to show for it atm
```
RUN_ID=tda-flutter3 python3 -m pytest -s mobile_native/android_flutter/test_checkout_flutter_android.py
======================================================= test session starts =======================================================
platform darwin -- Python 3.12.10, pytest-8.4.1, pluggy-1.6.0
rootdir: /Users/kosty/home/emp4/tda
plugins: …
```
=> [tda] add Flutter + cleanup
