package-lock.json
package.json
src/index.js
yarn.lock

tested:
- Performance
- Release Health
- <SentryRoute> for parameterized transactions
https://sentry.io/organizations/will-captel/discover/results/?field=transaction&field=http.url&field=event.type&field=project&field=user.display&field=release&field=timestamp&id=9142&name=Transactions+and+Resource+ID&project=5711949&query=&sort=-timestamp&statsPeriod=24h&widths=-1&widths=406&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1

Install sentry

---

flask/db.py
package-lock.json
package.json
src/components/Products.js
src/index.js
yarn.lock

- js sdk 6.5.0
- Products now served by /products frontend and backend Flask route
- Product image URL's served along with Product object from database
- Product images come from Cloud Storage Bucket
- Known issue of Navigation transactions not appearing anymore. Escalating with developers.

Database Tables for serving Products

---

README.md
deploy.sh
flask/db.py
flask/main.py
src/components/Products.js
src/components/products/1.js

Product reviews are now served to the `/products` route.
Product reviews data is in a database table called `reviews` and the `review.productId` is the foreignKey.
The product's average rating is now shown on the product in the frontend. It's computed by taking all the reviews for the product and dividing by the total number of reviews.
This is a N+1 Query because there's a Reviews query run for each product. This is considered the "before state".
The `/product` page still uses product data that's hard coded into `src/assets` and `src/components/products`, which makes it good for developing (i.e. you don't have to start up the server and connect to the database).
So any changes to the UI for better displaying the rating in `product.js`, can easily be applied over to the `products.js` …

Product Reviews

---

README.md
flask/main.py
src/components/Checkout.js
src/components/Complete.js
src/components/CompleteError.js
src/components/Products.js
src/components/ProductsJoin.js
src/index.js

- pass 200 or 500 response info from /checkout into CompleteError.js or Complete.js (order confirmation)
- shopping cart data passed from frontend to backend /checkout
- shopping cart is accessible via React Context
/checkout error response looks like:
and /checkout error response in sentry-demos/tracing looks like:
they're the same
https://dev.to/brad_beggs/handling-react-form-submit-with-redirect-async-await-for-the-beyond-beginner-57of
https://www.pluralsight.com/guides/how-to-transition-to-another-route-on-successful-async-redux-action
https://reactjs.org/docs/forms.html
```
// this.history.push doesn't do anything. It only works if you remove async operations (await) above, and remove the event.preventDefault()
// Can't use  `static history = useHistory()` because we're in a Function …
```

Shopping Cart - Purchase, Process and Error Handling

---

tests/README.md
tests/conftest.py
tests/create_cron_job.sh
tests/endpoints.yaml
tests/frontend_tests/test_add_to_cart.py
tests/requirements.txt
tests/script.sh

https://app.saucelabs.com/tests/b2d5d2a5e4444c9fa326fdeef581b410
^ succesful test

adding checkout test

---

.gitignore
flask/db.py
flask/main.py
flask/utils.py

Custom spans for /products /products-join /checkout.
- only insturment inside of get_products? or inside of endpoint as well
- `/checkout.get_inventory` or `checkout.get_inventory` or `get_inventory`

trends and spans endpoints

---

CODEOWNERS

- Add CODEOWNERS file so I can try to integrate with our Sentry projects

Add Github Codeowners file

---

CODEOWNERS

- Without `/` wasn't working, so trying this.

Update codeowners file to read ownership from root

---

CODEOWNERS

Updating contents of codeowners file for troubleshooting as I try to set up.

Troubleshooting codeowners file

---

CODEOWNERS

More codeowners updates

---

README.md
spring-boot/README.md
spring-boot/pom.xml
spring-boot/src/main/java/com/sentrydemos/springboot/AppController.java
spring-boot/src/main/java/com/sentrydemos/springboot/Application.java
spring-boot/src/main/java/com/sentrydemos/springboot/DatabaseHelper.java
spring-boot/src/main/java/com/sentrydemos/springboot/Item.java

Update Sentry SDKs Spring Boot.
Update products-join endpoint spans to match Flask's.
Added setTracesSampler to avoid sampling OPTIONS transactions
sentry-spring-boot-starter: 5.5.0 to 5.5.2
sentry-logback: 5.5.0 to 5.5.2
Application Monitoring Staging React w/ Spring Boot [URL](https://tmp-simon-react-dot-sales-engineering-sf.appspot.com/?se=simon&backend=springboot)
Spring Boot [/checkout Trace](https://sentry.io/organizations/testorg-az/performance/trace/ddfbf940f17a4649956795ff9037baf3/)
Spring Boot [/products-join Transaction Event Details](https://sentry.io/organizations/testorg-az/performance/simon-java-spring-boot:c51bb93c1d8a467f8a5a09ea0187373e/)
No OPTIONS transactions appearing in Spring Boot [Performance page](https://sentry.io/organizations/testorg-az/performance/?project=595 …

Java Spring Boot - Sentry SDK version update and products-join

---

tests/conftest.py
tests/mobile_native/ios/test_checkout_ios.py
tests/release_version_manager.py

Also added in test that adds 4 Plant Moods to cart + Clicks on cart + clicks on purchase

Add support for running tests on native ios app

---

express/server.js
spring-boot/src/main/java/com/sentrydemos/springboot/AppController.java

Adding some headers to be sent to the ruby API when requests go through from the spring-boot backend.

send user,se,customerType headers on call to Ruby api for Express.js and Spring-boot

---

deploy.sh

deploy.sh: minor changes to make it work in CI / GitHub Actions environment

---

react/src/components/About.js
react/src/components/Products.js
react/src/components/ProductsJoin.js
react/src/utils/index.js
react/src/utils/time.js

```
["22.11.1","22.11.2","22.11.3","22.11.4","22.11.5","22.12.1","22.12.2","22.12.3","22.12.4","22.12.5","23.1.1","23.1.2","23.1.3","23.1.4","23.1.5","23.2.1","23.2.2","23.2.3","23.2.4","23.3.1"].forEach((x,i) => console.log(isOddReleaseWeek(x)));
VM117:1 false
VM117:1 true
VM117:1 false
VM117:1 true
VM117:1 false
VM117:1 true
VM117:1 false
VM117:1 true
VM117:1 false
VM117:1 true
VM117:1 false
VM117:1 true
VM117:1 false
VM117:1 true
VM117:1 false
VM117:1 true
VM117:1 false
VM117:1 true
VM117:1 false
VM117:1 true
```
Sample transactions (/about):
https://sentry.io/organizations/kosty-org/performance/am-react:ec360739067b404ca8a470c2ad078868/?project=4504057062227968&query=id%3Ae46d73aa207741b1aa5eb83569afd025&statsPeriod=24h&transaction=%2Fabout …

Trends: random delay /about + /products-join on odd/even weeks

---

react/src/components/Home.js
react/src/index.js

Example affected issue: 
https://sentry.io/organizations/testorg-az/issues/3726114815/?environment=production&project=5808623&query=is%3Aunresolved&referrer=issue-stream
Root cause is create-react-app/webpack boilerplate inlined javascript in pageload HTML that has no source map.
./deploy.sh --env=staging react
https://sentry.io/organizations/testorg-az/issues/3726125024/events/bafb4dbbdb784ab99dd174a88d591d60/?project=5808623

[react] fix for source map processing error for &crash= utils/errors.js

---

react/src/components/Home.js
react/src/index.js

This reverts commit c0e69d3ad041d57fd07cda2ddbef8ced3fe3638e, reversing changes made to 26bfc6317ca318d18cf3d95e8a96d43cda0382a1.

Revert "Merge pull request #111 from sentry-demos/fix-proc-error"

---

react/build.sh

https://create-react-app.dev/docs/advanced-configuration/
https://github.com/facebook/create-react-app/blob/f92c37a6e6636ed1650ffd976c6881f59b1be803/packages/react-scripts/config/webpack.config.js#L56
https://github.com/facebook/create-react-app/blob/f92c37a6e6636ed1650ffd976c6881f59b1be803/packages/react-scripts/config/webpack.config.js#L627-L632
[/?crash=1](https://sentry.io/organizations/testorg-az/issues/3730885144/events/9bd3c2e812dc4a3f942d3a517f4de322/?project=5808623) - note unhandled, no processing error
[/checkout 500](https://sentry.io/organizations/testorg-az/issues/3707039875/events/ce35d9bc4f7f4a6aad3fdc0a54ed68b6/?project=5808623) - still looks as expected, no change

[react] Fix missing source processing error by disabling webpack inline bootstrap code

---

react/src/components/Organization.js
react/src/index.js

missed a small detail on the previous pull request.
previous PR had right changes but was based on an older version of master.

[react] organization route update

---

bin/proj_slug_from_dsn.sh

Not used in deploy.sh or any other code as of right now

[bin] proj_slug_from_dsn.sh

---

react/src/components/Checkout.js

```
./deploy.sh react --env=local
```
[Sample event](https://sentry.io/organizations/kosty-org/issues/3864716515/events/479326e1db5a49b3bf9cbd8d6a209f1a/?project=4504057062227968)
1. Verified highlighted stacktrace line has `throw`, not `Sentry.captureException()`
2. Verified event's transaction is `Submit Checkout Form`
3. Verified `/error` page ("We're having some trouble") displayed in browser when testing locally

[react] A more realistic error throwing exception for checkout (attempt 3)

---

aspnetcore/Controllers/ApiController.cs
aspnetcore/Controllers/CheckoutController.cs
aspnetcore/Controllers/ConnectController.cs
aspnetcore/Controllers/HandledController.cs
aspnetcore/Controllers/OrganizationController.cs
aspnetcore/Controllers/ProductsController.cs
aspnetcore/Controllers/ProductsJoinController.cs
aspnetcore/Controllers/ReviewsController.cs
aspnetcore/Controllers/SuccessController.cs
aspnetcore/Controllers/UnhandledController.cs
aspnetcore/Models/Inventory.cs
aspnetcore/Models/Products.cs
aspnetcore/Models/Reviews.cs
aspnetcore/Models/Tools.cs
aspnetcore/Models/hardwarestoreContext.cs
aspnetcore/Program.cs
aspnetcore/Startup.cs
aspnetcore/appsettings.json.template
aspnetcore/aspnetcore.csproj

Testing URL:
[Front-end](https://staging-application-monitoring-react-dot-sales-engineering-sf.appspot.com/?backend=aspnetcore)
[staging .net project](https://testorg-az.sentry.io/issues/3934420698/?project=4504461107396608&referrer=project-issue-stream)
Also possible to send ?se=angelo or other name

Initialise sentry

---

aspnetcore/Controllers/ApiController.cs
aspnetcore/Controllers/CheckoutController.cs
aspnetcore/Controllers/ConnectController.cs
aspnetcore/Controllers/HandledController.cs
aspnetcore/Controllers/OrganizationController.cs
aspnetcore/Controllers/ProductsController.cs
aspnetcore/Controllers/ProductsJoinController.cs
aspnetcore/Controllers/ReviewsController.cs
aspnetcore/Controllers/SuccessController.cs
aspnetcore/Controllers/UnhandledController.cs
aspnetcore/Models/Inventory.cs
aspnetcore/Models/Products.cs
aspnetcore/Models/Reviews.cs
aspnetcore/Models/Tools.cs
aspnetcore/Models/hardwarestoreContext.cs
aspnetcore/Startup.cs

https://staging-application-monitoring-react-dot-sales-engineering-sf.appspot.com/?backend=aspnetcore
- Retrieves the products (not slowed down yet)
- throws 500 error at checkout

Get dotnet running

---

react/package-lock.json
react/package.json

https://staging-application-monitoring-react-dot-sales-engineering-sf.appspot.com/
https://testorg-az.sentry.io/issues/3967160798/events/c68c1922e12e430293aa02126b8b8c3a/?project=4504708328325120

[react] SDK upgrade 7.29.0 -> 7.39.0

---

express/package-lock.json
express/package.json
express/server.js

From staging:
https://testorg-az.sentry.io/issues/3827876991/events/cd16b21a3c3643128a85b1b8b1e6665b/?project=4504330844635136#exception

Upgrade node sdk to 7.41 + enable stack locals

---

tests/conftest.py
tests/desktop_web/test_about_employees.py
tests/desktop_web/test_about_employees_vue.py
tests/desktop_web/test_add_to_cart.py
tests/desktop_web/test_add_to_cart_join.py
tests/desktop_web/test_homepage.py
tests/desktop_web/test_homepage_vue.py
tests/desktop_web/test_organization.py
tests/desktop_web/test_subscribe_vue.py

Just cleaning up some duplicated code

[tda] refactor: endpoints and selenium_endpoint fixtures

---

react/src/utils/errors.js
tests/conftest.py
tests/desktop_web/test_about_employees.py
tests/desktop_web/test_about_employees_vue.py
tests/desktop_web/test_add_to_cart.py
tests/desktop_web/test_add_to_cart_join.py
tests/desktop_web/test_homepage.py
tests/desktop_web/test_homepage_vue.py
tests/desktop_web/test_organization.py
tests/desktop_web/test_subscribe_vue.py
tests/mobile_native/android_react_native/test_captureexception_react_native_android.py
tests/mobile_native/android_react_native/test_capturemessage_react_native_android.py
tests/mobile_native/android_react_native/test_homescreen_react_native_android.py

[tda + react] Repeatable output between TDA runs

---

tests/build.sh
tests/canary.sh
tests/conftest.py
tests/deploy_tda.sh
tests/desktop_web.sh
tests/jobs/desktop_web.sh
tests/jobs/mobile_native.sh
tests/loop.sh
tests/mobile_native.sh
tests/requirements.txt
tests/run.sh
tests/script.sh
tests/stop.sh

- verified new code in /home/kosty_maleyev/tests
- verified new processes running (incl. canary), old killed
```
./deploy_tda.sh
Checking ssh connection can be established...
Checking state of current deployment...
Copying code to remote directory...
Code copied.
No need to install requirements, because no changes to requirements.txt, env exists on remote host and is not empty.
Killing any currently running TDA processes...
25161
25441
25512
Starting TDA...
Running canary for jobs/desktop_web.sh ...
. pid: 26104
. sleeping for 15 seconds...
[OK] Seems to be running fine.
. canaries are let to run their course, so process may linger for a few minutes.
Running canary for jobs/mobile_native.sh ...
. pid: 26157
. sleeping for 15 seconds...
[OK] Seems to be running fine.
. canaries are let to …
```

[tda] Fully automated code deployment + TDA restart

---

aspnetcore/appsettings.json.template
aspnetcore/build.sh
deploy.sh
spring-boot/build.sh

This is necessary to get Suspect Commits to work
spring-boot: https://kosty-org.sentry.io/issues/4062385380/events/58640b4da7a342f98b4f27095193ae49/
aspnetcore: https://kosty-org.sentry.io/issues/4062377644/events/c436e46b850f4d72b954ed8f69e932aa/

[spring-boot, aspnetcore] Send release info

---

tests/desktop_web/test_checkout.py

https://testorg-az.sentry.io/performance/application-monitoring-javascript:51f1278d77c74d4e8142dfc630b4d7c6/?project=5808623&query=se%3Atesting123&referrer=performance-transaction-summary&statsPeriod=14d&transaction=%2Fproducts&unselectedSeries=p100%28%29

checkout test directly to /products

---

tests/deploy_tda.sh

[tda] deploy_tda.sh: Fix permissions error by not rsyncing permissions, timestamps, etc.

---

react/src/components/Cart.js
react/src/components/Checkout.js
react/src/components/CompleteError.js
react/src/components/Footer.js
react/src/components/Home.js
react/src/components/Nav.js
react/src/components/Product.js
react/src/components/ProductCard.js
react/src/components/products.css
react/src/index.css
react/src/index.js

https://kosty-org.sentry.io/replays/react:2e6f8b825140484b9c7e96d46726ca5b/?referrer=%2Fissues%2F%3AgroupId%2F&t=34&t_main=console
**NOTE: logo and images missing in Replay most likely because it's localhost, should work in production**

[react] Replay unmask nav, form field names; change background

---

react/src/components/CompleteError.js
react/src/index.js

http://localhost:3000/?userFeedback=true
https://kosty-org.sentry.io/issues/4146411302/events/d3280367cc7646fbbd0b53f4e18f3755/?project=4504057062227968&referrer=user-feedback

[react] show User Feeback dialog (after brief delay) when &userFeedback=true

---

aspnetcore/AppMiddleware.cs
aspnetcore/AppUtils.cs
aspnetcore/Controllers/CheckoutController.cs
aspnetcore/Controllers/ProductsController.cs
aspnetcore/Program.cs

Sample event in staging:
https://testorg-az.sentry.io/performance/staging-application-monitoring-aspnetcore:9af8b7065e1141b78a81fe4bb5aae71b/?transaction=GET+Products

ASP.NET Core backend - Add HTTP client request

---

express/db.js
flask/src/db.py
spring-boot/src/main/java/com/sentrydemos/springboot/DatabaseHelper.java

Requires following to be created in DB
```
CREATE VIEW weekly_promotions AS SELECT CAST(pg_sleep(0.25) as TEXT);
CREATE VIEW backorder_inventory AS SELECT CAST(pg_sleep(0.2) as TEXT);
CREATE VIEW product_bundles AS SELECT CAST(pg_sleep(0.0625) as TEXT);
```
```
./deploy.sh --env=local react flask express spring-boot
```
http://localhost:3000/?backend=flask
http://localhost:3000/products
http://localhost:3000/?backend=express
http://localhost:3000/products
http://localhost:3000/?backend=springboot
http://localhost:3000/products

[flask,express,spring-boot] nicer SQL queries for perf. issues with "sleepy views"

---

express/package-lock.json

```
./deploy.sh --env=production express
```

[express] fix broken build by updating package-lock.json to match package.json

---

flask/src/main.py

Goal: make `main.py` testable so that don't get errors from missing env. variables like PORT when importing from `pytest`.
This particular solution is necessary because the app is run differently locally and in the cloud. In the cloud `gunicorn` just takes module + Flask app name (`app`) and doesn't call `run()` that we supply.
```
./deploy.sh --env=local flask
```
http://127.0.0.1:8080/products
https://kosty-org.sentry.io/issues/?project=4504465890803712&query=&referrer=issue-stream&stream_index=0
```
./deploy.sh --env=staging flask
```
https://staging-application-monitoring-flask-dot-sales-engineering-sf.appspot.com/products
https://testorg-az.sentry.io/issues/?project=4504331063525376&query=is%3Aunresolved&referrer=issue-list&statsPeriod=14d

[flask] move env init to Flask app to make more unit-testable

---

aspnetcore/Controllers/ProductsController.cs

To demo slow products loading, add some random slowness.

Slow down aspnetcore products

---

.github/workflows/auto-deploy.yml
bin/release.sh

[release] Deploy React when time for new calendar release even if no changes

---

flask/requirements.txt
flask/src/main.py

- https://testorg-az.sentry.io/performance/staging-backend-python:120b1357088e4681aee4e3a443ad4196/?project=4504331063525376&transaction=products
- https://testorg-az.sentry.io/issues/4117859548/?end=2023-08-01T02%3A25%3A07&project=4504331063525376&query=&referrer=issue-stream&start=2023-08-01T01%3A25%3A07&stream_index=0

[flask] fix for prev change; 1.14.0 -> 1.29.0

---

react/package-lock.json
react/package.json
react/src/components/Products.js

This reverts commit 9a3adf01f8533caa053315fb0680f51b2cb94e5d.
Reason: /products get stuck forever loading regardless of backend (tested w/ flask and laravel)

Revert "feat(profiling): introduce a large list render (#238)"

---

react/package-lock.json
react/package.json
react/src/components/Products.js

Array length of 250/4 is a float hence the invalid array length. Lower it down to 200

feat(react): render problem

---

bin/sed_inplace.sh
deploy.sh

./deploy.sh --env=production spring-boot

[springboot, platform] make sed -i work on Linux, fixing Spring Boot deploy

---

react/src/components/Products.js

This reverts commit 6fc72e26a5820ae3492ac3611da73a1ffd985bb5.
Something changed about the cart or something else in the /checkout payload which made checkout succeed in some of the backends. Before we make changes to all backends so that they fail regardless of request body we need to temporarily roll this back so that demo flow is not broken for SEs.
https://staging-application-monitoring-react-dot-sales-engineering-sf.appspot.com/?backend=express
checkout fails as expected

Revert "feat(react): render problem (#245)"

---

react/src/index.js

This is needed to generate some Replay sessions for a particular user. This is needed to demo https://github.com/getsentry/hackweek-zendesk-replay but can have other use cases. Currently all users are generated randomly and we don't have control over them.
https://testorg-az.sentry.io/issues/4418158082/?project=4504708328325120&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=0

[react] add ?userEmail= query parameter

---

react/src/components/Footer.js
react/src/components/footer.css
react/src/index.js

Previously clicking on Subscribe in the footer of home page would create a pageload with the email form parameter making it hard to generate rage clicks. This change makes the button truly unresponsive without changing anything visually.
https://staging-application-monitoring-react-dot-sales-engineering-sf.appspot.com/

[react] Rage Clicks: detach 'Subscribe' button from form

---

express/README.md
express/db.js
express/package-lock.json
express/package.json
express/server.js
express/utils.js

Per [notion](https://www.notion.so/sentry/Empower-How-to-Contribute-3190417cf9b14e7c895fb352d5c28bd6#7fe9647576904be69985bc4592d7b898)

Auto format `express/` directory

---

react/src/components/Checkout.js
react/src/index.js

https://staging-application-monitoring-react-dot-sales-engineering-sf.appspot.com/?se=tda
https://staging-application-monitoring-react-dot-sales-engineering-sf.appspot.com/?se=kosty

Re-do "fill form with default values" so it works with TDA

---

react/src/components/Products.js

https://github.com/sentry-demos/empower/issues/252
This reverts commit 28a1123a77c9b83050bba6f67b931aaddc33e3b8.
which in turn reverted https://github.com/sentry-demos/empower/pull/245
https://staging-application-monitoring-react-dot-sales-engineering-sf.appspot.com/

Revert "Revert "feat(react): render problem (#245)" (#249)"

---

react/config-overrides.js
react/package-lock.json
react/package.json

Adds react-prod-sourcemaps plugin that remaps react to include sourcemaps. This should improve both error and profiling stack traces

fix(build): add react-prod-sourcemaps

---

flask/requirements.txt

this version supports python3.11

upgrade psycopg2-binary

---

express/server.js

- Apparently we were not forcing express failures as was meant to be addressed previously in https://github.com/sentry-demos/empower/issues/251
- This fixes that and forces a checkout failure for express
- Tested on staging, see below
- [error event on staging](https://demo.sentry.io/discover/staging-backend-express:cb0d3b5aeca848bbab1539cf967d7764/)

force express checkout failure

---

bin/projects_changed_bw_commits.sh

exclude mini-relay from deployment

---

tda/requirements.txt

this is needed to fix some breakages in local chromedriver

[tda]: upgrade selenium version

---

tda/build.sh
tda/conftest.py
tda/deploy_tda.sh

fix deploy_tda.sh by upgrading Ubuntu

---

react/package-lock.json
react/package.json
react/src/components/Footer.js

resolves https://github.com/sentry-demos/empower/issues/308 
Now when you click the subscribe button on the footer for react projects, an error happens and we display a fallback UI
This is done via react error boundaries.

feat(react): Add error boundary to form container

---

flask/src/main.py

[flask] fix missing SC by touching code raising the error

---

flask/src/main.py

update before_send to read se from event

---

docker-compose.yml
mini-relay/app.py
mini-relay/data/.gitignore

this collects the data but doesn't do any classification-by-test of it yet

[mini-relay] collect data

---

tda/conftest.py

I forgot to delete this when adding the config files

[tda] remove old browser config

---

docker-compose.yml
ruby/main.rb

now ruby can be collected with mock data

[ruby] allow overriding dsn

---

tda/mobile_native/android_react_native/test_captureexception_react_native_android.py
tda/mobile_native/android_react_native/test_capturemessage_react_native_android.py
tda/mobile_native/android_react_native/test_checkout_react_native_android.py
tda/mobile_native/android_react_native/test_homescreen_react_native_android.py
tda/mobile_native/android_react_native/test_nativecrash_react_native_android.py
tda/mobile_native/android_react_native/test_uncaughtthrownerror_react_native_android.py
tda/mobile_native/android_react_native/test_unhandledpromiserejection_react_native_android.py

I tested this and made sure all these tests pass against the new sentry_react_native_release

fix tests and use better selectors

---

tda/deploy_tda.sh

added test file
deployed
deleted test file
deployed

[tda] deploy_tda: fix permissions regressions when deleting files

---

flask/requirements.txt
flask/src/main.py

Enable [Query Source](https://docs.sentry.io/product/performance/queries/#query-sources) for Flask service
And bump sdk to `1.39.1`
[Query Summary Example](https://team-se.sentry.io/performance/database/spans/span/496db2bc74e1e116/?project=4506510403960832&statsPeriod=1h)
[Flagship errors and transactions
](https://team-se.sentry.io/discover/homepage/?field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&name=All+Events&project=4506510403960832&query=&sort=-timestamp&statsPeriod=1h&yAxis=count%28%29)

Enable DB Query Source in Flask service

---

react/package-lock.json
react/package.json

react-app-rewired seems to break HMR so dont use it unless we are bundling the code.

fix(react): fix cra

---

react/package-lock.json
react/package.json
react/src/components/Checkout.js
react/src/components/Products.js
react/src/index.js
react/src/utils/measureRequestDuration.js

Bump `@sentry/react` to `7.93.0`.
Add custom metrics in react demo.
- closes https://github.com/sentry-demos/empower/issues/367

feat(react): Add custom metrics

---

flask/requirements.txt

this allows it to be installable locally

[flask] make requirements 3.12 compatible

---

flask/app.yaml.template
flask/requirements.txt
flask/src/db.py

https://github.com/sentry-demos/empower/pull/399 has broken auto-deploy due to
`ERROR: No matching distribution found for numpy==1.26.0` ([GitHub Action logs
](https://github.com/sentry-demos/empower/actions/runs/7968152424/job/21751962787))
https://staging-application-monitoring-react-dot-sales-engineering-sf.appspot.com/products?se=kosty_gae-py312&backend=flask

WIP [flask] update GAE Python 3.8 -> 3.12 to fix broken deploy after dependencies bump

---

.github/workflows/deploy_tda.yml
tda/deploy_tda.sh

already reviewed and approved in https://github.com/sentry-demos/empower/pull/435
merged into branch instead of mainline by mistake earleir
merging properly now

[platform] GitHub Actions workflow to deploy TDA (fix merge)

---

aspnetcore/Program.cs

./deploy.sh --env=local aspnetcore react
[example event](https://kosty.sentry.io/issues/4997761715/events/815378cda5684d7a896834e91851e6b6/)

[aspnetcore] capture request body

---

README.md

Update README.md with User Feedback instructions

---

codecov.yml

Additional codecov plumbing required for proper demo
- 2 Components (see codecov comment below -- it now shows components)

Codecov plumbing

---

README.md
aspnetcore/AppMiddleware.cs
aspnetcore/Controllers/ProductsController.cs
aspnetcore/Empower.Backend.csproj
mini-relay/requirements.txt

Bumped the SDK and updated the `User` to `SentryUser` due to a breaking change in the mayor bump.

Bump .NET SDK

---

codecov.yml

Moving out of demo PR to clean it up.

update codecov.yml to include components

---

react/src/components/Checkout.jsx

very small change, no need to test!

I think we can delete this variable, it's not needed

---

flask/requirements.txt
flask/src/main.py

tested as part of https://github.com/sentry-demos/empower/pull/573

[flask] upgrade sentry-python 1.40.0 -> 2.14.0; handle SE "supertag" better wrt grouping

---

react/src/tests/Reducer.test.js

Was breaking auto-deploy https://github.com/sentry-demos/empower/actions/runs/11023851879/job/30615935888

[react] fix unit test broken by Crit. Exp. PR and blocking deploy

---

tda/desktop_web/test_checkout.py

end the test at /cart (as no items were added and therefore checkout can't happen)

don't try to checkout if CExp.ADD_TO_CART_JS_ERROR

---

react/src/components/Cart.jsx
react/src/components/Checkout.jsx
react/src/utils/utils.js

tested locally that flow works
didn't check metrics

React better metrics

---

tda/desktop_web/test_checkout.py

just hoping to get some insights into how often those things time out since we already have it...

[tda] catch right Selenium errors, simplify abandoned metrics

---

next/app/layout.jsx
next/app/products-sc/page.jsx
next/app/products/page.jsx
next/lib/data.js
next/package-lock.json
next/package.json
next/src/components/Nav.jsx
next/ui/loader.jsx
next/ui/product-catalog.jsx
next/ui/sentry-query-initializer.jsx

* Uploaded hardware db to vercel postgres
* Created /producs-sc page with server components 
* Separates fetching logic and display logic
* Artificial timeout does nothing since the route gets cached by next js
** (await new Promise((resolve) => setTimeout(resolve, 2000));)

/products-sc server side component

---

.github/workflows/run_codecov_on_pull_request.yml

Changed Codecov settings to upload analysis to master branch
I didn't exclude other projects' tests as well for pushing to master branch.

Changed Codecov settings to upload analysis to master branch

---

next/src/app/cart/page.jsx
next/src/ui/HomeContent.jsx
next/src/ui/products/ProductCard.jsx
next/src/utils/store.js

Changes
- moved redux store creation into its own file
- create the store as a singleton so the same instance is used everywhere
How to test
- in vercel, add items to cart. Go to cart. See correct total

fix no cart total in vercel

---

next/lib/data.js
next/package-lock.json
next/package.json
next/sentry.client.config.js
next/sentry.server.config.js
next/src/app/cart/page.jsx
next/src/ui/products/ProductCard.jsx

**Changes**
- enabled node profiling on server config
- removed come leftover console log debug statements
**Testing**
- profiles should appear in sentry.io, however these can take several days to appear and require a critical mass of traffic

added profiling

---

.github/workflows/run_codecov_on_pull_request.yml

fixes https://github.com/codecov/engineering-team/issues/3367

fix: update the codecov workflow

---

README.md
react/src/components/Footer.jsx
react/src/index.css
react/src/index.js
tda/desktop_web/test_subscribe.py

- Updates the subcribe to put an email on the queue via flask
- Adds error_boundary url param
- Adds a test to hit subscribe
Testing
- Tested locally w/ and without error_boundary

Adding subscribe queueing to react

---

bin/envsubst.sh

see https://github.com/sentry-demos/empower/pull/697

[platform] envsubst.sh (forgot to add to #697)

---

next/lib/data.js
next/sentry.server.config.js

removed node profiling because it was preventing server spans from reaching sentry

removed node profiling from next

---

.github/workflows/auto-deploy.yml
bin/list_deployable_projects.sh
bin/projects_changed_bw_commits.sh

had to refactor by moving the logic to find all deployable projects into a separate script so it can be used in both auto-deploy.yml and projects_changed_bw_commits.sh

[platform] deploy ALL projects when auto-deploy triggered manually

---

.github/workflows/cleanup_projects.yml

Break things by line
added `sentaur-survivors` project to it

don't delete sentaur survivors

---

.github/workflows/cleanup_projects.yml

Reverts sentry-demos/empower#718

Revert "don't delete sentaur survivors"

---

.github/workflows/cleanup_projects.yml

don't delete sentaur-survivors and leaderboard

---

aspnetcore/Controllers/ProductsController.cs
aspnetcore/Program.cs

More context:
* https://www.jamescrosswell.dev/posts/async-detecting-blocking-calls/
* https://github.com/getsentry/sentry-dotnet/pull/2709
* https://x.com/brungarc/status/1711484812702171309
If suspect commit is set up, should point to my commit? 🤞

detect blocking calls on aspnet core

---

bin/envsubst.sh

fixes https://github.com/sentry-demos/empower/actions/runs/13914950356/job/38936202103
`./deploy.sh --env=staging flask`

[platform] fix new envsubst.sh that was breaking on ubuntu-22.04

---

laravel/app.yaml.template
laravel/composer.json
laravel/composer.lock

`./deploy.sh --env=staging laravel`

[laravel] update dependencies to fix build

---

bin/sentry-release.sh
deploy.sh

`./deploy.sh --env=staging flask`
https://demo.sentry.io/releases/application.monitoring.flask%4025.3.4/?project=4508968134377472

[flask] hopefully long-term fix for suspect commmits

---

flask/app.py

whitespace change, shipping without review

[flask] touch file to trigger deploy/new release to test suspect commits

---

.github/workflows/auto-deploy.yml
.github/workflows/run_codecov_on_pull_request.yml

fixes https://github.com/sentry-demos/empower/actions/runs/14459285705/job/40548753413

[platform] bump node version in CI workflows to match recent upgrade

---

tda/config.yaml

https://staging-react.empower-plant.com/
https://github.com/sentry-demos/empower-config/pull/33
See: https://github.com/sentry-demos/empower-config/pull/33

[tda] switch TDA to empower-plant.com domain

---

next/sentry.client.config.js
react/src/index.js
vue/src/main.js

https://github.com/sentry-demos/empower/pull/790
https://github.com/sentry-demos/empower-config/pull/33

[react,next,vue] add empower-plant.com to tracePropagationTargets

---

auto-deploy.exclude

all 3 have been fixed since they were disabled

Auto-deploy Laravel, Aspnetcore and Spring-boot

---

.github/workflows/auto-deploy.yml

Also add to deploy yaml (added to codecov one before)

---

.github/workflows/auto-deploy.yml
flask/app.yaml.template

- Env vars were not being included in build and causing failures
- Added to yaml
- Deployed locally to prod already so this is to make future deployments not break

Fix flask build by explicitly including env vars in yaml

---

.github/workflows/cleanup_projects.yml

Unreal demo: https://github.com/sentry-demos/unreal

add unreal to cleanup_projects.yml

---

tda/mobile_native/android_react_native/test_captureexception_react_native_android.py
tda/mobile_native/android_react_native/test_capturemessage_react_native_android.py
tda/mobile_native/android_react_native/test_checkout_react_native_android.py
tda/mobile_native/android_react_native/test_nativecrash_react_native_android.py
tda/mobile_native/android_react_native/test_uncaughtthrownerror_react_native_android.py
tda/mobile_native/android_react_native/test_unhandledpromiserejection_react_native_android.py

[tda,react-native] tune sleep duration for Android

---

tda/jobs/desktop_web.sh
tda/jobs/mobile_native.sh

Reattempting this after upgrading gcp host to 2GB

Reapply "[tda] increase number of threads 8 -> 16 (#833)" (#837)

---

react/package-lock.json
react/package.json
react/src/index.js

logs enabled on demo.sentry.io

Enable Sentry logs for react

---

flask/src/db.py

Fix sql vuln

---

tda/loop.sh

[tda] fix timestamp in loop.sh logs

---

tda/build.sh
tda/deploy_tda.sh

[tda] fix permissions when deleting venv when created by another user

---

flask/src/main.py

additionally apply this fix
`./deploy.sh --env=local react flask`
=> successful checkout

[flask] have only 1 bug in checkout

---

flask/requirements.txt
flask/run.sh

started breaking for me locally
@lukemun could you please test locally on your mac?
`./deploy.sh --env=local flask`
`./deploy.sh --env=staging flask` -> https://staging-flask.empower-plant.com/products

[flask] fix running locally: numpy version + gunicorn inst.of flask run

---

laravel/composer.lock

fixes https://github.com/sentry-demos/empower/actions/runs/16333963685/job/46142330786
`./deploy.sh --env=local laravel`
`./deploy.sh --env=staging laravel`

[laravel] run composer update to fix deploy

---

laravel/build.sh
laravel/composer.lock
laravel/run.sh

```
rm -rf vendor/*
./deploy.sh --env=staging laravel
```
https://staging-laravel.empower-plant.com/products-join

[laravel] Fix deploy attempt 2 - only install dependencies when run locally

---

tda/deploy_tda.sh
tda/jobs/desktop_web.sh
tda/jobs/mobile_native.sh
tda/requirements.txt

[tda] use pytest-timeout to prevent stuck tests

---

.github/workflows/cleanup_projects.yml

Updated cleanup_projects.yml with flutter project

Updated cleanup_projects.yml with flutter project

---

tda/desktop_web/test_cexp_checkout.py

apply promo code only once per batch (so it's truly 1 time per day)

[tda] promo code logs: once per batch

---

next/lib/data.js

Reducing iterations of getIterator function in order to improve performance. Will revert in another PR to demo profiling regressed functions feature

improved performance of getIterator function

---

README.md
next/lib/data.js
next/sentry.server.config.js
next/src/utils/backendrouter.js

- Added Sentry logger
- Cleaned up config values
- Intentionally regressed getIterator function
- Added clearer instructions for running demo locally

Add sentry log
